# Generated by Django 3.2.3 on 2024-11-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IND', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ind_game',
            name='player4notes',
            field=models.TextField(blank=True),
        ),
    ]
