# Generated by Django 5.2.9 on 2026-04-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IND', '0001_initial'),
        ('Lobby', '0107_profile_preferredrnboptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='INDMainTournament',
            fields=[
            ],
            options={
                'verbose_name': 'IND Main Tournament',
                'verbose_name_plural': 'IND Main Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
        migrations.CreateModel(
            name='INDMiniTournament',
            fields=[
            ],
            options={
                'verbose_name': 'IND Mini Tournament',
                'verbose_name_plural': 'IND Mini Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
    ]
