# Generated by Django 3.2.3 on 2025-01-19 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("IND", "0004_auto_20250118_1514"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ind_game",
            name="creator",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="INDgame_creator_relName",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ind_game",
            name="host",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="INDgame_host_relName",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
