# Generated by Django 5.2.7 on 2025-12-18 14:39

import Lobby.sharedFunctions.sharedRefs
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IND", "0011_alter_ind_game_id_alter_ind_tournament_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ind_game",
            name="latestUpdate",
            field=models.CharField(
                db_index=True,
                default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow,
                max_length=15,
            ),
        ),
    ]
