# Generated by Django 5.2.9 on 2026-01-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IND', '0014_alter_ind_game_gamepace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ind_game',
            name='deleteGameVotes',
        ),
    ]
