# Generated by Django 5.2.9 on 2026-01-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IND', '0015_remove_ind_game_deletegamevotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ind_game',
            name='deleteGameVotes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
