# Generated by Django 5.2.9 on 2026-02-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IND', '0021_indgame'),
        ('Lobby', '0077_remove_game_relatedindtournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ind_game',
            name='relatedTournament',
        ),
        migrations.DeleteModel(
            name='IND_Tournament',
        ),
    ]
