# Generated by Django 5.2.9 on 2026-02-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IND', '0022_remove_ind_game_relatedtournament_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IND_Game',
        ),
    ]
