# Generated from ./AQY/vueAQY/src/js/AQYreference.js
# Total blocks synced: 2
PHASE_FIRST_CITY = 0
PHASE_ALL_RISE = 1
PHASE_CITY_BUILDING = 2
PHASE_TURN_ORDER = 3
PHASE_COUNTRYSIDE_BUILDING = 4
PHASE_STORE_GOODS = 5
PHASE_HARVEST = 6
PHASE_EXPLORE = 7
PHASE_FAMINE = 8
PHASE_POLLUTION = 9
PHASE_CHECK_VICTORY = 10
PHASE_GAME_OVER = 11
PRE_PHASE_OFFSET = 10
PRE_PHASE_STORE_GOODS = 15
PRE_PHASE_HARVEST = 16
PRE_PHASE_EXPLORE = 17
PRE_PHASE_FAMINE = 18
PRE_PHASE_POLLUTION = 19
HIST_CITY_PLAYER_TRADE = 13
