# NB THIS IS MADE MANUALLY
# FCM is a legacy format game
PHASE_SETUP_RESTAURANT1 = 0
PHASE_SETUP_RESTAURANT2 = 1
PHASE_SETUP_RESERVE = 2
PHASE_RESTRUCTURING = 3
PHASE_TURN_ORDER = 4
PHASE_WORKING_DAY = 5
PHASE_DINNERTIME = 6
PHASE_PIZZA_BOMB = 11
PHASE_PAYDAY = 7
PHASE_MARKETING_CAMPAIGNS = 8
PHASE_COFFE_SHOP_MS = 12
PHASE_CLEAN_UP = 9
PHASE_GAME_OVER = 10
PHASE_SETUP_MODULES = 13
PHASE_URBAN_PLANNING = 14
PHASE_CHOOSE_CEO_BONUS = 15

# PRE-PHASES
PREPHASE_PAYDAY = 17
PREPHASE_CLEAN_UP = 19

# Starting options
SO_SHORT_GAME = 1
SO_NO_MILESTONES = 2
SO_NO_CEO_MILESTONE = 3
SO_ALLOW_SURRENDER = 5
SO_NO_RADIO_MILESTONE = 6
#SO_MAP_SEED = 7
SO_HARD_CHOICES = 8
SO_FRY_CHEFS = 9
SO_KIMCHI = 10
SO_SUSHI = 11
SO_NOODLES = 12
SO_GOURMET = 13
SO_MOVIE_STARS = 14
SO_MASS_MARKETERS = 15
SO_NIGHT_SHIFT = 16
SO_RURAL_MARKETERS = 17
SO_NEW_DISTRICTS = 18
SO_NEW_DISTRICTS_APP = 181
SO_NEW_DISTRICTS_ALL = 182
SO_NEW_DISTRICTS_PARK = 183
SO_COFFEE = 19
SO_KETCHUP_MS = 20
SO_NEW_MS = 21
SO_LOBBYISTS = 22
SO_RESERVE_PRICE = 23
# Chinese Expansion
SO_URBAN_PLANNING = 40
SO_URBAN_PLANNING_PLUS = 41
SO_JAZZ_MUSICIANS = 42
SO_DUMPLINGS = 43
SO_DELIVERY_DRIVERS = 44
SO_HAWKERS = 45

# Other options
SO_AUTO_ENABLE_REWINDS = 99
SO_STRICT_PAYDAY_FRIDGE = 101
SO_SANDBOX_MODE = 103
SO_RANDOM_MODULES = 200
SO_RANDOM_MODULES_OLD_MS = 201
SO_RANDOM_MODULES_NEW_MS = 202
SO_DRAFT_MODULES = 205
SO_MIN_RANDOM_MODULES = 210
SO_MAX_RANDOM_MODULES = 211
SO_DRAFT_MODULE_BREAKER = 300
SO_DRAFT_SKIP_MODULE = 999

# Flag to use new code
TS_USE_NEW_CODE = 1744974000000
