services:
  db:
    image: mysql:9.5
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: obs
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    restart: always
    ports:
      - "3307:3306"

  obs:
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - db
    #  - cns
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: password 

    env_file:
      - .env

    command: ["sh", "./initial_db_setup.sh"]

  cns:
    build:
      context: ./CNS/vueCNS
    working_dir: /app
    volumes:
      # Mount the vue source code here
      - ./CNS/vueCNS:/app
    ports:
      # Expose the Vite dev server port
      - "3012:3012"

volumes:
  data:
