services:
  db:
    image: mysql:9.5
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: obs
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    restart: always
    ports:
      - "3307:3306"

  services:
  # ... (db service configuration) ...

  obs:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - db
      - cns
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: password 
    command: ["./initial_db_setup.sh"] 

  # ... (cns service configuration) ...

volumes:
  data:

  cns:
    build:
      context: CNS/vueCNS
    ports:
      - "3012:3012"

volumes:
  data:
