# Generated by Django 3.2.3 on 2023-02-13 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HC_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=120)),
                ('gameStatus', models.CharField(max_length=30)),
                ('latestUpdate', models.CharField(max_length=30)),
                ('startingOptions', models.CharField(blank=True, max_length=70)),
                ('currentPlayers', models.CharField(blank=True, max_length=100)),
                ('serverTurnOrder', models.CharField(blank=True, max_length=20)),
                ('seatOffset', models.PositiveSmallIntegerField()),
                ('maxPlayers', models.PositiveSmallIntegerField()),
                ('turn', models.PositiveSmallIntegerField(default=0)),
                ('phase', models.PositiveSmallIntegerField(default=0)),
                ('kickoutDuration', models.PositiveSmallIntegerField(default=200)),
                ('gamePace', models.PositiveSmallIntegerField(default=20)),
                ('created', models.CharField(max_length=30)),
                ('rewindConsent', models.CharField(max_length=10)),
                ('statsExcludeConsent', models.CharField(max_length=10)),
                ('player0currentMoveTime', models.CharField(blank=True, max_length=30)),
                ('player0currentMoveData', models.CharField(blank=True, max_length=1000)),
                ('player1currentMoveTime', models.CharField(blank=True, max_length=30)),
                ('player1currentMoveData', models.CharField(blank=True, max_length=1000)),
                ('player2currentMoveTime', models.CharField(blank=True, max_length=30)),
                ('player2currentMoveData', models.CharField(blank=True, max_length=1000)),
                ('player3currentMoveTime', models.CharField(blank=True, max_length=30)),
                ('player3currentMoveData', models.CharField(blank=True, max_length=1000)),
                ('player4currentMoveTime', models.CharField(blank=True, max_length=30)),
                ('player4currentMoveData', models.CharField(blank=True, max_length=1000)),
                ('chatData', models.TextField(default='{"name":"WelcomeBot","timestamp":1676264378000,"message":"Welcome to Horseless Carriage Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},')),
                ('player0notes', models.TextField(blank=True)),
                ('player1notes', models.TextField(blank=True)),
                ('player2notes', models.TextField(blank=True)),
                ('player3notes', models.TextField(blank=True)),
                ('player4notes', models.TextField(blank=True)),
                ('gameData', models.TextField(blank=True)),
                ('rewindData', models.TextField(blank=True)),
                ('rewindTempData', models.TextField(blank=True)),
                ('statsExcludedGame', models.BooleanField(default=False)),
                ('allPlayers', models.ManyToManyField(related_name='HCallPlayersRelName', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HCgame_creator_relName', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HCgame_host_relName', to=settings.AUTH_USER_MODEL)),
                ('invitedPlayers', models.ManyToManyField(blank=True, related_name='HCinvitedPlayersRelName', to=settings.AUTH_USER_MODEL)),
                ('kickedPlayers', models.ManyToManyField(blank=True, related_name='HCkickedPlayersRelName', to=settings.AUTH_USER_MODEL)),
                ('missingPlayers', models.ManyToManyField(blank=True, related_name='HCmissingPlayersRelName', to=settings.AUTH_USER_MODEL)),
                ('playersWithChatNotification', models.ManyToManyField(blank=True, related_name='HCplayersWithChatNotificationName', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HCgame_winner_relName', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
