# Generated by Django 3.2.3 on 2023-02-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HC", "0002_alter_hc_game_chatdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hc_game",
            name="chatData",
            field=models.TextField(
                default='{"name":"WelcomeBot","timestamp":1676445876000,"message":"Welcome to Horseless Carriage Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'
            ),
        ),
        migrations.AlterField(
            model_name="hc_game",
            name="rewindConsent",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
