# Generated by Django 3.2.3 on 2023-03-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0007_alter_hc_game_chatdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hc_game',
            name='chatData',
            field=models.TextField(default='{"name":"WelcomeBot","timestamp":1680234136000,"message":"Welcome to Horseless Carriage Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'),
        ),
    ]
