# Generated by Django 3.2.3 on 2023-07-27 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HC', '0008_alter_hc_game_chatdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='hc_game',
            name='tournamentGame',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hc_game',
            name='chatData',
            field=models.TextField(default='{"name":"WelcomeBot","timestamp":1690432606000,"message":"Welcome to Horseless Carriage Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'),
        ),
        migrations.CreateModel(
            name='HC_Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournamentName', models.CharField(max_length=120)),
                ('tournamentStatus', models.CharField(choices=[('OP', 'Open'), ('IP', 'In Progress'), ('FN', 'Finished')], default='OP', max_length=2)),
                ('tournamentType', models.CharField(choices=[('RR', 'Rounds'), ('KO', 'Knockout'), ('TL', 'Two Lives')], default='OP', max_length=2)),
                ('startingOptions', models.CharField(blank=True, default='', max_length=70)),
                ('maxTournamentPlayers', models.PositiveSmallIntegerField()),
                ('maxGamePlayers', models.PositiveSmallIntegerField()),
                ('roundsBeforeKnockout', models.PositiveSmallIntegerField(default=4)),
                ('winnersData', models.TextField(blank=True)),
                ('created', models.CharField(default=1690432606000, max_length=30)),
                ('tournamentProgressionData', models.TextField(blank=True)),
                ('tournamentSideData', models.TextField(blank=True)),
                ('tournamentPointsData', models.TextField(blank=True)),
                ('nextRoundPlayers', models.ManyToManyField(blank=True, related_name='currentRoundPlayersRelName_HC', to=settings.AUTH_USER_MODEL)),
                ('startingPlayers', models.ManyToManyField(blank=True, related_name='startingPlayersRelName_HC', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hc_game',
            name='relatedTournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_relName', to='HC.hc_tournament'),
        ),
    ]
