# Generated by Django 3.2.3 on 2023-08-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HC", "0010_auto_20230803_0716"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hc_game",
            name="chatData",
            field=models.TextField(
                default='{"name":"WelcomeBot","timestamp":1693462737000,"message":"Welcome to Horseless Carriage Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'
            ),
        ),
        migrations.AlterField(
            model_name="hc_tournament",
            name="created",
            field=models.CharField(default=1693462737000, max_length=30),
        ),
    ]
