# Generated by Django 3.2.3 on 2023-10-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0012_auto_20230923_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hc_game',
            name='chatData',
            field=models.TextField(default='{"name":"WelcomeBot","timestamp":1696329419000,"message":"Welcome to Horseless Carriage Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'),
        ),
        migrations.AlterField(
            model_name='hc_tournament',
            name='created',
            field=models.CharField(default=1696329419000, max_length=30),
        ),
    ]
