# Generated by Django 3.2.3 on 2023-12-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HC", "0019_auto_20231226_0516"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hc_game",
            name="chatData",
            field=models.TextField(
                default='{"name":"WelcomeBot","timestamp":1703568468000,"message":"Welcome to Horseless Carriage Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'
            ),
        ),
        migrations.AlterField(
            model_name="hc_tournament",
            name="created",
            field=models.CharField(default=1703568468000, max_length=30),
        ),
    ]
