# Generated by Django 3.2.3 on 2023-12-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HC", "0022_alter_hc_tournament_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hc_tournament",
            name="created",
            field=models.CharField(default=1703598969000, max_length=30),
        ),
    ]
