# Generated by Django 3.2.3 on 2024-01-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HC", "0025_alter_hc_tournament_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hc_game",
            name="gameDescription",
            field=models.CharField(
                blank=True, db_collation="utf8mb4_general_ci", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="hc_game",
            name="gameName",
            field=models.CharField(db_collation="utf8mb4_general_ci", max_length=120),
        ),
    ]
