# Generated by Django 3.2.3 on 2024-02-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0026_auto_20240120_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='hc_game',
            name='kickoutFlexiData',
            field=models.TextField(blank=True),
        ),
    ]
