# Generated by Django 3.2.3 on 2024-12-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HC", "0027_hc_game_kickoutflexidata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hc_game",
            name="gameName",
            field=models.CharField(
                blank=True, db_collation="utf8mb4_general_ci", max_length=120
            ),
        ),
    ]
