# Generated by Django 3.2.3 on 2025-08-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0030_alter_hc_tournament_tournamenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='hc_game',
            name='deleteGameVotes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
