# Generated by Django 5.2.7 on 2025-12-18 14:39

import Lobby.sharedFunctions.sharedRefs
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HC", "0036_alter_hc_game_id_alter_hc_tournament_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hc_game",
            name="latestUpdate",
            field=models.CharField(
                db_index=True,
                default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow,
                max_length=15,
            ),
        ),
    ]
