# Generated by Django 5.2.9 on 2026-01-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HC", "0037_alter_hc_game_latestupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hc_game",
            name="gamePace",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="hc_game",
            name="maxPlayers",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="hc_game",
            name="startingOptions",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
