# Generated by Django 5.2.9 on 2026-01-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0038_alter_hc_game_gamepace_alter_hc_game_maxplayers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hc_game',
            name='deleteGameVotes',
        ),
    ]
