# Generated by Django 5.2.9 on 2026-01-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0040_hc_game_deletegamevotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hc_game',
            name='startingMap',
            field=models.CharField(blank=True, max_length=190),
        ),
    ]
