# Generated by Django 5.2.9 on 2026-01-14 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("HC", "0043_hc_game_playerorderseed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hc_game",
            name="serverTurnOrder",
        ),
    ]
