# Generated by Django 5.2.9 on 2026-01-14 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("HC", "0044_remove_hc_game_serverturnorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hc_game",
            name="seatOffset",
        ),
    ]
