# Generated by Django 5.2.9 on 2026-02-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0047_hc_game_automoves'),
        ('Lobby', '0083_remove_game_relatedfcmtournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCgame',
            fields=[
            ],
            options={
                'verbose_name': 'HC_Game',
                'verbose_name_plural': 'HC_Games',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.game',),
        ),
    ]
