# Generated by Django 5.2.9 on 2026-03-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lobby', '0100_alter_game_gamecode_alter_main_tournament_gamecode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGZgame',
            fields=[
            ],
            options={
                'verbose_name': 'TGZ_Game',
                'verbose_name_plural': 'TGZ_Games',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.game',),
        ),
        migrations.CreateModel(
            name='TGZMiniTournament',
            fields=[
            ],
            options={
                'verbose_name': 'TGZ Mini Tournament',
                'verbose_name_plural': 'TGZ Mini Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.mini_tournaments',),
        ),
    ]
