# Generated by Django 3.2.3 on 2023-12-19 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TGZ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgz_game',
            name='created',
            field=models.CharField(default='1702955400000', max_length=30),
        ),
        migrations.AlterField(
            model_name='tgz_game',
            name='creator',
            field=models.ForeignKey(default='admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TGZgame_creator_relName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tgz_game',
            name='host',
            field=models.ForeignKey(default='admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TGZgame_host_relName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tgz_game',
            name='latestUpdate',
            field=models.CharField(default='1702955400000', max_length=30),
        ),
        migrations.AlterField(
            model_name='tgz_game',
            name='zoomLevels',
            field=models.CharField(default='[240, 240, 240, 240, 240]', max_length=30),
        ),
    ]
