# Generated by Django 3.2.3 on 2023-12-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGZ', '0002_auto_20231219_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgz_game',
            name='startingMap',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='tgz_game',
            name='created',
            field=models.CharField(default='1703041490000', max_length=30),
        ),
        migrations.AlterField(
            model_name='tgz_game',
            name='latestUpdate',
            field=models.CharField(default='1703041490000', max_length=30),
        ),
    ]
