# Generated by Django 5.2.9 on 2026-04-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0107_profile_preferredrnboptions'),
        ('TGZ', '0002_delete_tgzminitournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGZMainTournament',
            fields=[
            ],
            options={
                'verbose_name': 'TGZ Main Tournament',
                'verbose_name_plural': 'TGZ Main Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
        migrations.CreateModel(
            name='TGZMiniTournament',
            fields=[
            ],
            options={
                'verbose_name': 'TGZ Mini Tournament',
                'verbose_name_plural': 'TGZ Mini Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
    ]
