# Generated by Django 3.2.3 on 2023-12-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGZ', '0003_auto_20231220_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgz_game',
            name='created',
            field=models.CharField(default='1703563512000', max_length=30),
        ),
        migrations.AlterField(
            model_name='tgz_game',
            name='latestUpdate',
            field=models.CharField(default='1703563512000', max_length=30),
        ),
    ]
