# Generated by Django 3.2.3 on 2023-12-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TGZ", "0008_auto_20231226_1337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tgz_game",
            name="created",
            field=models.CharField(default="1703598969000", max_length=30),
        ),
        migrations.AlterField(
            model_name="tgz_game",
            name="latestUpdate",
            field=models.CharField(default="1703598969000", max_length=30),
        ),
    ]
