# Generated by Django 3.2.3 on 2024-01-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TGZ", "0013_tgz_game_statsexcludeconsent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tgz_game",
            name="statsExcludeConsent",
            field=models.CharField(default="00000", max_length=5),
        ),
    ]
