# Generated by Django 3.2.3 on 2024-01-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGZ', '0014_alter_tgz_game_statsexcludeconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgz_game',
            name='externalTournamentGame',
            field=models.BooleanField(default=False),
        ),
    ]
