# Generated by Django 3.2.3 on 2024-01-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGZ', '0015_tgz_game_externaltournamentgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgz_game',
            name='gameName',
            field=models.CharField(blank=True, db_collation='utf8mb4_general_ci', default='[TGZ Game]', max_length=120),
        ),
    ]
