# Generated by Django 3.2.3 on 2024-02-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGZ', '0017_alter_tgz_game_gamedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgz_game',
            name='kickoutFlexiData',
            field=models.TextField(blank=True),
        ),
    ]
