# Generated by Django 3.2.3 on 2024-08-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TGZ", "0018_tgz_game_kickoutflexidata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tgz_game",
            name="gameName",
            field=models.CharField(
                blank=True, db_collation="utf8mb4_general_ci", max_length=120
            ),
        ),
    ]
