# Generated by Django 3.2.3 on 2025-08-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0045_alter_mini_tournaments_created"),
        ("TGZ", "0021_auto_20250816_0740"),
    ]

    operations = [
        migrations.AddField(
            model_name="tgz_game",
            name="relatedMiniTournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="minitournamentTGZ_relName",
                to="Lobby.mini_tournaments",
            ),
        ),
    ]
