# Generated by Django 5.2.7 on 2025-11-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Lobby", "0048_alter_mini_tournaments_tournamenttype_and_more"),
        ("TGZ", "0022_tgz_game_relatedminitournament"),
    ]

    operations = [
        migrations.AddField(
            model_name="tgz_game",
            name="relatedMainTournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintournamentTGZ_relName",
                to="Lobby.main_tournaments",
            ),
        ),
    ]
