# Generated by Django 5.2.7 on 2025-12-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TGZ", "0025_alter_tgz_game_creator_alter_tgz_game_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tgz_game",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
