# Generated by Django 5.2.9 on 2026-01-13 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0055_alter_main_tournament_gamecode'),
        ('TGZ', '0027_alter_tgz_game_latestupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGZMiniTournament',
            fields=[
            ],
            options={
                'verbose_name': 'TGZ Mini Tournament',
                'verbose_name_plural': 'TGZ Mini Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.mini_tournaments',),
        ),
    ]
