# Generated by Django 5.2.9 on 2026-01-14 08:00

import Lobby.sharedFunctions.sharedRefs
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TGZ", "0028_tgzminitournament"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tgz_game",
            name="gamePace",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="tgz_game",
            name="latestUpdate",
            field=models.CharField(
                db_index=True,
                default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow,
                max_length=15,
            ),
        ),
    ]
