# Generated by Django 5.2.9 on 2026-01-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGZ', '0031_alter_tgz_game_startingmap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgz_game',
            name='activeVotes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
