# Generated by Django 5.2.9 on 2026-01-31 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0069_alter_game_relatedtournament'),
        ('TGZ', '0032_tgz_game_activevotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGZgame',
            fields=[
            ],
            options={
                'verbose_name': 'TGZ_Game',
                'verbose_name_plural': 'TGZ_Games',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.game',),
        ),
    ]
