# Generated by Django 5.2.9 on 2026-02-08 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TGZ", "0033_tgzgame"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TGZ_Game",
        ),
    ]
