# Generated by Django 3.2.3 on 2025-08-16 07:40

import Lobby.sharedFunctions.sharedRefs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RNB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnb_game',
            name='created',
            field=models.CharField(default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow, max_length=15),
        ),
        migrations.AlterField(
            model_name='rnb_game',
            name='gameStatus',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('WAITING', 'WAITING'), ('PRIVATE', 'PRIVATE'), ('ACTIVE', 'ACTIVE'), ('FINISHED', 'FINISHED')], default='AVAILABLE', max_length=9),
        ),
        migrations.AlterField(
            model_name='rnb_game',
            name='latestUpdate',
            field=models.CharField(default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow, max_length=15),
        ),
    ]
