# Generated by Django 5.2.9 on 2026-04-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RNB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNBmap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_players', models.PositiveSmallIntegerField(default=1)),
                ('max_players', models.PositiveSmallIntegerField(default=6)),
                ('hexData', models.JSONField(blank=True, help_text='JUST the hex data, in format [ [q,r,rotation,terrainID], ...]]', null=True)),
                ('customElements', models.JSONField(blank=True, help_text='Preset starting locations, built bridges, etc etc', null=True)),
                ('highscores', models.JSONField(blank=True, default=list, null=True)),
                ('isOfficial', models.BooleanField(default=False)),
            ],
        ),
    ]
