# Generated by Django 5.2.9 on 2026-04-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RNB', '0002_rnbmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rnbmap',
            name='max_players',
        ),
        migrations.RemoveField(
            model_name='rnbmap',
            name='min_players',
        ),
        migrations.AddField(
            model_name='rnbmap',
            name='playerCount',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
