# Generated by Django 5.2.9 on 2026-04-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RNB', '0003_remove_rnbmap_max_players_remove_rnbmap_min_players_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rnbmap',
            options={'verbose_name': 'RNB Map', 'verbose_name_plural': 'RNB Maps'},
        ),
        migrations.AddField(
            model_name='rnbmap',
            name='map_number',
            field=models.PositiveIntegerField(editable=False, help_text='Permanent unique ID for this map across all installations.', unique=True),
        ),
    ]
