# Generated by Django 5.2.9 on 2026-04-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0107_profile_preferredrnboptions'),
        ('RNB', '0004_alter_rnbmap_options_rnbmap_map_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNBMainTournament',
            fields=[
            ],
            options={
                'verbose_name': 'RNB Main Tournament',
                'verbose_name_plural': 'RNB Main Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
        migrations.CreateModel(
            name='RNBMiniTournament',
            fields=[
            ],
            options={
                'verbose_name': 'RNB Mini Tournament',
                'verbose_name_plural': 'RNB Mini Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
    ]
