# Generated by Django 5.2.9 on 2026-05-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RNB', '0005_rnbmaintournament_rnbminitournament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rnbmap',
            old_name='map_number',
            new_name='uniqueID',
        ),
        migrations.RemoveField(
            model_name='rnbmap',
            name='customElements',
        ),
    ]
