# Generated by Django 5.2.9 on 2026-05-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RNB', '0006_rename_map_number_rnbmap_uniqueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnbmap',
            name='uniqueID',
            field=models.PositiveIntegerField(help_text='Permanent unique ID for this map across all installations.', unique=True),
        ),
    ]
