# Generated by Django 5.2.9 on 2026-05-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RNB', '0007_alter_rnbmap_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnbmap',
            name='uniqueID',
            field=models.PositiveIntegerField(blank=True, help_text='Permanent unique ID for this map across all installations.', null=True, unique=True),
        ),
    ]
