# Generated by Django 5.2.9 on 2026-05-07 05:46

import Lobby.sharedFunctions.sharedRefs
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RNB', '0008_alter_rnbmap_uniqueid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rnbmap',
            name='highscores',
        ),
        migrations.CreateModel(
            name='RNBMapScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.PositiveIntegerField(unique=True)),
                ('score', models.PositiveIntegerField(db_index=True)),
                ('timeStamp', models.CharField(default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow, max_length=15)),
                ('map_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='RNB.rnbmap', to_field='uniqueID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'timeStamp'],
            },
        ),
    ]
