# Generated by Django 5.2.9 on 2026-05-07 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0108_alter_gameplayer_notes'),
        ('RNB', '0009_remove_rnbmap_highscores_rnbmapscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rnbmapscore',
            options={'ordering': ['-score', 'timeStamp'], 'verbose_name': 'RNB Map Score', 'verbose_name_plural': 'RNB Map Scores'},
        ),
        migrations.RemoveField(
            model_name='rnbmapscore',
            name='game_id',
        ),
        migrations.AddField(
            model_name='rnbmapscore',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rnb_scores', to='Lobby.game'),
            preserve_default=False,
        ),
    ]
