# Generated by Django 5.2.9 on 2026-05-19 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RNB', '0010_alter_rnbmapscore_options_remove_rnbmapscore_game_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rnbmap',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rnb_maps', to=settings.AUTH_USER_MODEL),
        ),
    ]
