# Generated by Django 5.2.9 on 2026-05-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RNB', '0011_rnbmap_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rnbmap',
            old_name='isOfficial',
            new_name='isVerified',
        ),
    ]
