# Generated by Django 5.2.9 on 2026-09-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RNB', '0012_rename_isofficial_rnbmap_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnbmap',
            name='playCount',
            field=models.IntegerField(default=0),
        ),
    ]
