# Generated by Django 5.2.9 on 2026-02-17 01:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0083_remove_game_relatedfcmtournament"),
        ("RNB", "0014_rnb_game_automoves"),
    ]

    operations = [
        migrations.CreateModel(
            name="RNBgame",
            fields=[],
            options={
                "verbose_name": "RNB_Game",
                "verbose_name_plural": "RNB_Games",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Lobby.game",),
        ),
    ]
