# Generated by Django 5.2.9 on 2026-02-17 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("RNB", "0015_rnbgame"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RNB_Game",
        ),
    ]
