# Generated by Django 5.2.9 on 2026-03-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BUS', '0026_delete_bus_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busgame',
            options={'verbose_name': 'BUS_Game', 'verbose_name_plural': 'BUS_Games'},
        ),
    ]
