CREATE OR REPLACE VIEW Lobby_all_games AS (
  SELECT 'FCM' AS gameCode,
         `FCM_fcm_game`.`id`,
         `FCM_fcm_game`.`gameName`,
         `FCM_fcm_game`.`gameDescription`,
         `FCM_fcm_game`.`gameStatus`,
         `FCM_fcm_game`.`latestUpdate`,
         `FCM_fcm_game`.`startingOptions`,
         `FCM_fcm_game`.`startingMap`,
         `FCM_fcm_game`.`currentPlayers`,
         `FCM_fcm_game`.`seatOffset`,
         `FCM_fcm_game`.`maxPlayers`,
         `FCM_fcm_game`.`turn`,
         `FCM_fcm_game`.`phase`,
         `FCM_fcm_game`.`kickoutDuration`,
         `FCM_fcm_game`.`gamePace`,
         `FCM_fcm_game`.`creator_id`,
         `FCM_fcm_game`.`host_id`,
         `FCM_fcm_game`.`created`,
--         `FCM_fcm_game`.`zoomLevels`,
--         `FCM_fcm_game`.`notificationSuppression`,
         `FCM_fcm_game`.`rewindConsent`,
         `FCM_fcm_game`.`statsExcludeConsent`,
         `FCM_fcm_game`.`chatData`,
--         `FCM_fcm_game`.`playersMoveData`,
         `FCM_fcm_game`.`player0notes`,
         `FCM_fcm_game`.`player1notes`,
         `FCM_fcm_game`.`player2notes`,
         `FCM_fcm_game`.`player3notes`,
         `FCM_fcm_game`.`player4notes`,
         `FCM_fcm_game`.`player5notes`,
         `FCM_fcm_game`.`gameData`,
         `FCM_fcm_game`.`rewindData`,
         `FCM_fcm_game`.`rewindTempData`,
         `FCM_fcm_game`.`relatedTournament_id`,
--         `FCM_fcm_game`.`relatedMiniTournament_id`,
         `FCM_fcm_game`.`statsExcludedGame`,
         `FCM_fcm_game`.`kickoutFlexiData`,
         `FCM_fcm_game`.`deleteGameVotes`
  FROM `FCM_fcm_game`
  UNION ALL
  SELECT 'HC' AS gameCode,
         `HC_hc_game`.`id`,
         `HC_hc_game`.`gameName`,
         `HC_hc_game`.`gameDescription`,
         `HC_hc_game`.`gameStatus`,
         `HC_hc_game`.`latestUpdate`,
         `HC_hc_game`.`startingOptions`,
         NULL AS startingMap,
         `HC_hc_game`.`currentPlayers`,
--         `HC_hc_game`.`serverTurnOrder`,
         `HC_hc_game`.`seatOffset`,
         `HC_hc_game`.`maxPlayers`,
         `HC_hc_game`.`turn`,
         `HC_hc_game`.`phase`,
         `HC_hc_game`.`kickoutDuration`,
         `HC_hc_game`.`gamePace`,
         `HC_hc_game`.`creator_id`,
         `HC_hc_game`.`host_id`,
         `HC_hc_game`.`created`,
         `HC_hc_game`.`rewindConsent`,
         `HC_hc_game`.`statsExcludeConsent`,
--         `HC_hc_game`.`player0currentMoveTime`,
--         `HC_hc_game`.`player0currentMoveData`,
--         `HC_hc_game`.`player1currentMoveTime`,
--         `HC_hc_game`.`player1currentMoveData`,
--         `HC_hc_game`.`player2currentMoveTime`,
--         `HC_hc_game`.`player2currentMoveData`,
--         `HC_hc_game`.`player3currentMoveTime`,
--         `HC_hc_game`.`player3currentMoveData`,
--         `HC_hc_game`.`player4currentMoveTime`,
--         `HC_hc_game`.`player4currentMoveData`,
         `HC_hc_game`.`chatData`,
         `HC_hc_game`.`player0notes`,
         `HC_hc_game`.`player1notes`,
         `HC_hc_game`.`player2notes`,
         `HC_hc_game`.`player3notes`,
         `HC_hc_game`.`player4notes`,
         NULL AS player5notes,
         `HC_hc_game`.`gameData`,
         `HC_hc_game`.`rewindData`,
         `HC_hc_game`.`rewindTempData`,
--         `HC_hc_game`.`tournamentGame`,
         `HC_hc_game`.`relatedTournament_id`,
         `HC_hc_game`.`statsExcludedGame`,
         `HC_hc_game`.`kickoutFlexiData`,
         `HC_hc_game`.`deleteGameVotes`
  FROM `HC_hc_game`
  UNION ALL
  SELECT
         'BUS' AS gameCode,
         `Bus_bus_game`.`id`,
         `Bus_bus_game`.`gameName`,
         `Bus_bus_game`.`gameDescription`,
         `Bus_bus_game`.`gameStatus`,
         `Bus_bus_game`.`latestUpdate`,
         `Bus_bus_game`.`startingOptions`,
         NULL AS startingMap,
         `Bus_bus_game`.`currentPlayers`,
         NULL AS seatOffset,
--         `Bus_bus_game`.`playerOrderSeed`,
         `Bus_bus_game`.`maxPlayers`,
         `Bus_bus_game`.`turn`,
         `Bus_bus_game`.`phase`,
         `Bus_bus_game`.`kickoutDuration`,
         `Bus_bus_game`.`gamePace`,
         `Bus_bus_game`.`creator_id`,
         `Bus_bus_game`.`host_id`,
         `Bus_bus_game`.`created`,
--         `Bus_bus_game`.`zoomLevels`,
         `Bus_bus_game`.`rewindConsent`,
         `Bus_bus_game`.`statsExcludeConsent`,
         `Bus_bus_game`.`chatData`,
         `Bus_bus_game`.`player0notes`,
         `Bus_bus_game`.`player1notes`,
         `Bus_bus_game`.`player2notes`,
         `Bus_bus_game`.`player3notes`,
         `Bus_bus_game`.`player4notes`,
         NULL AS player5notes,
         `Bus_bus_game`.`gameData`,
         `Bus_bus_game`.`rewindData`,
         `Bus_bus_game`.`rewindTempData`,
--         `Bus_bus_game`.`tournamentGame`,
         `Bus_bus_game`.`relatedTournament_id`,
         `Bus_bus_game`.`statsExcludedGame`,
         `Bus_bus_game`.`kickoutFlexiData`,
         `Bus_bus_game`.`deleteGameVotes`
  FROM `Bus_bus_game`
  UNION ALL
  SELECT
         'TGZ' AS gameCode,
         `TGZ_tgz_game`.`id`,
         `TGZ_tgz_game`.`gameName`,
         `TGZ_tgz_game`.`gameDescription`,
         `TGZ_tgz_game`.`gameStatus`,
         `TGZ_tgz_game`.`latestUpdate`,
         `TGZ_tgz_game`.`startingOptions`,
         `TGZ_tgz_game`.`startingMap`,
         `TGZ_tgz_game`.`currentPlayers`,
         NULL AS seatOffset,
--         `TGZ_tgz_game`.`playerOrderSeed`,
         `TGZ_tgz_game`.`maxPlayers`,
         `TGZ_tgz_game`.`turn`,
         `TGZ_tgz_game`.`phase`,
         `TGZ_tgz_game`.`kickoutDuration`,
         `TGZ_tgz_game`.`gamePace`,
         `TGZ_tgz_game`.`creator_id`,
         `TGZ_tgz_game`.`host_id`,
         `TGZ_tgz_game`.`created`,
--         `TGZ_tgz_game`.`autoMoves`,
--         `TGZ_tgz_game`.`zoomLevels`,
         NULL AS rewindConsent,
         `TGZ_tgz_game`.`statsExcludeConsent`,
         `TGZ_tgz_game`.`chatData`,
         `TGZ_tgz_game`.`player0notes`,
         `TGZ_tgz_game`.`player1notes`,
         `TGZ_tgz_game`.`player2notes`,
         `TGZ_tgz_game`.`player3notes`,
         `TGZ_tgz_game`.`player4notes`,
         NULL AS player5notes,
         `TGZ_tgz_game`.`gameData`,
         `TGZ_tgz_game`.`rewindData`,
         `TGZ_tgz_game`.`rewindTempData`,
--         `TGZ_tgz_game`.`tournamentGame`,
         NULL AS relatedTournament_id,
--         `TGZ_tgz_game`.`externalTournamentGame`,
--         `TGZ_tgz_game`.`relatedMainTournament_id`,
         `TGZ_tgz_game`.`statsExcludedGame`,
         `TGZ_tgz_game`.`kickoutFlexiData`,
--         `TGZ_tgz_game`.`relatedMiniTournament_id`,
         NULL AS deleteGameVotes
  FROM `TGZ_tgz_game`
  UNION ALL
  SELECT 'CNS' AS gameCode,
         `CNS_cns_game`.`id`,
         `CNS_cns_game`.`gameName`,
         `CNS_cns_game`.`gameDescription`,
         `CNS_cns_game`.`gameStatus`,
         `CNS_cns_game`.`latestUpdate`,
         `CNS_cns_game`.`startingOptions`,
         NULL AS startingMap,
         `CNS_cns_game`.`currentPlayers`,
         NULL AS seatOffset,
--         `CNS_cns_game`.`playerOrderSeed`,
         `CNS_cns_game`.`maxPlayers`,
         `CNS_cns_game`.`turn`,
         `CNS_cns_game`.`phase`,
         `CNS_cns_game`.`kickoutDuration`,
         `CNS_cns_game`.`gamePace`,
         `CNS_cns_game`.`creator_id`,
         `CNS_cns_game`.`host_id`,
         `CNS_cns_game`.`created`,
--         `CNS_cns_game`.`zoomLevels`,
         NULL AS rewindConsent,
         `CNS_cns_game`.`statsExcludeConsent`,
         `CNS_cns_game`.`chatData`,
         `CNS_cns_game`.`player0notes`,
         `CNS_cns_game`.`player1notes`,
         `CNS_cns_game`.`player2notes`,
         `CNS_cns_game`.`player3notes`,
         NULL AS player4notes,
         NULL AS player5notes,
         `CNS_cns_game`.`gameData`,
         `CNS_cns_game`.`rewindData`,
         `CNS_cns_game`.`rewindTempData`,
         NULL AS relatedTournament_id,
         `CNS_cns_game`.`statsExcludedGame`,
         `CNS_cns_game`.`kickoutFlexiData`,
         NULL AS deleteGameVotes
  FROM CNS_cns_game
  UNION ALL
  SELECT 'AQY' AS gameCode,
         `AQY_aqy_game`.`id`,
         `AQY_aqy_game`.`gameName`,
         `AQY_aqy_game`.`gameDescription`,
         `AQY_aqy_game`.`gameStatus`,
         `AQY_aqy_game`.`latestUpdate`,
         `AQY_aqy_game`.`startingOptions`,
         `AQY_aqy_game`.`startingMap`,
         `AQY_aqy_game`.`currentPlayers`,
         NULL AS seatOffset,
--         `AQY_aqy_game`.`playerOrderSeed`,
         `AQY_aqy_game`.`maxPlayers`,
         `AQY_aqy_game`.`turn`,
         `AQY_aqy_game`.`phase`,
         `AQY_aqy_game`.`kickoutDuration`,
         `AQY_aqy_game`.`gamePace`,
         `AQY_aqy_game`.`creator_id`,
         `AQY_aqy_game`.`host_id`,
         `AQY_aqy_game`.`created`,
--         `AQY_aqy_game`.`zoomLevels`,
         NULL AS rewindConsent,
         `AQY_aqy_game`.`statsExcludeConsent`,
--         `AQY_aqy_game`.`player0currentMoveTime`,
--         `AQY_aqy_game`.`player0currentMoveData`,
--         `AQY_aqy_game`.`player1currentMoveTime`,
--         `AQY_aqy_game`.`player1currentMoveData`,
--         `AQY_aqy_game`.`player2currentMoveTime`,
--         `AQY_aqy_game`.`player2currentMoveData`,
--         `AQY_aqy_game`.`player3currentMoveTime`,
--         `AQY_aqy_game`.`player3currentMoveData`,
         `AQY_aqy_game`.`chatData`,
         `AQY_aqy_game`.`player0notes`,
         `AQY_aqy_game`.`player1notes`,
         `AQY_aqy_game`.`player2notes`,
         `AQY_aqy_game`.`player3notes`,
         NULL AS player4notes,
         NULL AS player5notes,
         `AQY_aqy_game`.`gameData`,
         `AQY_aqy_game`.`rewindData`,
         `AQY_aqy_game`.`rewindTempData`,
--         `AQY_aqy_game`.`tournamentGame`,
         `AQY_aqy_game`.`relatedTournament_id`,
         `AQY_aqy_game`.`statsExcludedGame`,
         `AQY_aqy_game`.`kickoutFlexiData`,
--         `AQY_aqy_game`.`playerTradeData`,
         `AQY_aqy_game`.`deleteGameVotes`
  FROM `AQY_aqy_game`
  UNION ALL
  SELECT 'IND' AS gameCode,
         `IND_ind_game`.`id`,
         `IND_ind_game`.`gameName`,
         `IND_ind_game`.`gameDescription`,
         `IND_ind_game`.`gameStatus`,
         `IND_ind_game`.`latestUpdate`,
         `IND_ind_game`.`startingOptions`,
         NULL AS startingMap,
         `IND_ind_game`.`currentPlayers`,
         NULL AS seatOffset,
--         `IND_ind_game`.`playerOrderSeed`,
         `IND_ind_game`.`maxPlayers`,
         `IND_ind_game`.`turn`,
         `IND_ind_game`.`phase`,
         `IND_ind_game`.`kickoutDuration`,
         `IND_ind_game`.`gamePace`,
         `IND_ind_game`.`creator_id`,
         `IND_ind_game`.`host_id`,
         `IND_ind_game`.`created`,
--         `IND_ind_game`.`zoomLevels`,
         NULL AS rewindConsent,
         NULL AS statsExcludeConsent,
         `IND_ind_game`.`chatData`,
         `IND_ind_game`.`player0notes`,
         `IND_ind_game`.`player1notes`,
         `IND_ind_game`.`player2notes`,
         `IND_ind_game`.`player3notes`,
         `IND_ind_game`.`player4notes`,
         NULL AS player5notes,
         `IND_ind_game`.`gameData`,
         `IND_ind_game`.`rewindData`,
         `IND_ind_game`.`rewindTempData`,
--         `IND_ind_game`.`tournamentGame`,
         `IND_ind_game`.`relatedTournament_id`,
         `IND_ind_game`.`statsExcludedGame`,
--         `IND_ind_game`.`playersPreMoveData`,
         `IND_ind_game`.`kickoutFlexiData`,
         `IND_ind_game`.`deleteGameVotes`
  FROM `IND_ind_game`
  UNION ALL
  SELECT 'KFW' AS gameCode,
         `KFW_kfw_game`.`id`,
         `KFW_kfw_game`.`gameName`,
         `KFW_kfw_game`.`gameDescription`,
         `KFW_kfw_game`.`gameStatus`,
         `KFW_kfw_game`.`latestUpdate`,
         `KFW_kfw_game`.`startingOptions`,
         NULL AS startingMap,
         `KFW_kfw_game`.`currentPlayers`,
         NULL AS seatOffset,
--         `KFW_kfw_game`.`playerOrderSeed`,
         `KFW_kfw_game`.`maxPlayers`,
         `KFW_kfw_game`.`turn`,
         `KFW_kfw_game`.`phase`,
         `KFW_kfw_game`.`kickoutDuration`,
         `KFW_kfw_game`.`gamePace`,
         `KFW_kfw_game`.`creator_id`,
         `KFW_kfw_game`.`host_id`,
         `KFW_kfw_game`.`created`,
--         `KFW_kfw_game`.`zoomLevels`,
         NULL AS rewindConsent,
         NULL AS statsExcludeConsent,
         `KFW_kfw_game`.`chatData`,
         `KFW_kfw_game`.`player0notes`,
         `KFW_kfw_game`.`player1notes`,
         `KFW_kfw_game`.`player2notes`,
         `KFW_kfw_game`.`player3notes`,
         `KFW_kfw_game`.`player4notes`,
         `KFW_kfw_game`.`player5notes`,
         `KFW_kfw_game`.`gameData`,
         `KFW_kfw_game`.`rewindData`,
         `KFW_kfw_game`.`rewindTempData`,
--         `KFW_kfw_game`.`serverData`,
--         `KFW_kfw_game`.`playersHiddenData`,
--         `KFW_kfw_game`.`playersMoveData`,
--         `KFW_kfw_game`.`tournamentGame`,
         NULL AS relatedTournament_id,
         `KFW_kfw_game`.`statsExcludedGame`,
         `KFW_kfw_game`.`kickoutFlexiData`,
         NULL AS deleteGameVotes
  FROM `KFW_kfw_game`
  UNION ALL
  SELECT 'WEB' AS gameCode,
         `WEB_web_game`.`id`,
         `WEB_web_game`.`gameName`,
         `WEB_web_game`.`gameDescription`,
         `WEB_web_game`.`gameStatus`,
         `WEB_web_game`.`latestUpdate`,
         `WEB_web_game`.`startingOptions`,
         NULL AS startingMap,
         `WEB_web_game`.`currentPlayers`,
         NULL AS seatOffset,
--         `WEB_web_game`.`playerOrderSeed`,
         `WEB_web_game`.`maxPlayers`,
         `WEB_web_game`.`turn`,
         `WEB_web_game`.`phase`,
         `WEB_web_game`.`kickoutDuration`,
         `WEB_web_game`.`gamePace`,
         `WEB_web_game`.`creator_id`,
         `WEB_web_game`.`host_id`,
         `WEB_web_game`.`created`,
--         `WEB_web_game`.`zoomLevels`,
         NULL AS rewindConsent,
         NULL AS statsExcludeConsent,
         `WEB_web_game`.`chatData`,
         `WEB_web_game`.`player0notes`,
         `WEB_web_game`.`player1notes`,
         `WEB_web_game`.`player2notes`,
         `WEB_web_game`.`player3notes`,
         NULL AS player4notes,
         NULL AS player5notes,
         `WEB_web_game`.`gameData`,
         `WEB_web_game`.`rewindData`,
         `WEB_web_game`.`rewindTempData`,
         NULL AS relatedTournament_id,
         `WEB_web_game`.`statsExcludedGame`,
         `WEB_web_game`.`kickoutFlexiData`,
         `WEB_web_game`.`deleteGameVotes`
  FROM `WEB_web_game`
);
