# Generated by Django 5.2.9 on 2026-10-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0116_tournament_startingmap'),
        ('WEB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WEBMainTournament',
            fields=[
            ],
            options={
                'verbose_name': 'WEB Main Tournament',
                'verbose_name_plural': 'WEB Main Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
        migrations.CreateModel(
            name='WEBMiniTournament',
            fields=[
            ],
            options={
                'verbose_name': 'WEB Mini Tournament',
                'verbose_name_plural': 'WEB Mini Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
    ]
