# Generated by Django 5.2.7 on 2025-10-06 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WEB", "0002_auto_20250926_1312"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="web_game",
            name="winner",
        ),
        migrations.AddField(
            model_name="web_game",
            name="winner",
            field=models.ManyToManyField(
                blank=True,
                related_name="WEBgame_winner_relName",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
