# Generated by Django 5.2.7 on 2025-11-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WEB", "0003_remove_web_game_winner_web_game_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="web_game",
            name="deleteGameVotes",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
