# Generated by Django 5.2.9 on 2026-01-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0009_alter_web_game_gamepace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_game',
            name='deleteGameVotes',
        ),
    ]
