# Generated by Django 5.2.9 on 2026-01-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0013_web_game_statsexcludeconsent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_game',
            name='activeVotes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
