# Generated by Django 3.2.3 on 2022-06-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FCM_Bug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bugGameData", models.TextField(blank=True)),
                ("bugDescription", models.TextField(blank=True)),
                ("timeStamp", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="FCM_Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chatData", models.TextField(blank=True)),
                ("timeStamp", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="FCM_Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gameName", models.CharField(max_length=30)),
                ("gameStatus", models.CharField(max_length=30)),
                ("gamePace", models.CharField(max_length=30)),
                ("latestUpdate", models.CharField(max_length=30)),
                ("startingOptions", models.CharField(blank=True, max_length=30)),
                ("gameData", models.TextField(blank=True)),
                ("seatOffset", models.PositiveSmallIntegerField()),
                ("maxPlayers", models.PositiveSmallIntegerField()),
                ("turn", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("phase", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("player0currentMoveTime", models.CharField(blank=True, max_length=30)),
                ("player0currentMoveData", models.CharField(blank=True, max_length=30)),
                ("player1currentMoveTime", models.CharField(blank=True, max_length=30)),
                ("player1currentMoveData", models.CharField(blank=True, max_length=30)),
                ("player2currentMoveTime", models.CharField(blank=True, max_length=30)),
                ("player2currentMoveData", models.CharField(blank=True, max_length=30)),
                ("player3currentMoveTime", models.CharField(blank=True, max_length=30)),
                ("player3currentMoveData", models.CharField(blank=True, max_length=30)),
                ("player4currentMoveTime", models.CharField(blank=True, max_length=30)),
                ("player4currentMoveData", models.CharField(blank=True, max_length=30)),
                ("player5currentMoveTime", models.CharField(blank=True, max_length=30)),
                ("player5currentMoveData", models.CharField(blank=True, max_length=30)),
                ("currentPlayers", models.CharField(blank=True, max_length=100)),
                ("created", models.CharField(max_length=30)),
            ],
        ),
    ]
