# Generated by Django 5.2.9 on 2026-04-16 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0001_initial'),
    ]

    operations = [
        # Leave this list empty! This used to remove FCM_miniT based on Lobby.miniT
    ]
