# Generated by Django 5.2.9 on 2026-04-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0002_delete_fcmminitournament'),
        ('Lobby', '0107_profile_preferredrnboptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMMainTournament',
            fields=[
            ],
            options={
                'verbose_name': 'FCM Main Tournament',
                'verbose_name_plural': 'FCM Main Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
        migrations.CreateModel(
            name='FCMMiniTournament',
            fields=[
            ],
            options={
                'verbose_name': 'FCM Mini Tournament',
                'verbose_name_plural': 'FCM Mini Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
    ]
