# Generated by Django 3.2.3 on 2022-07-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0003_alter_fcm_game_startingoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm_game',
            name='startingMap',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
