# Generated by Django 3.2.3 on 2022-07-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0004_fcm_game_startingmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcm_game",
            name="rewindData",
            field=models.TextField(blank=True),
        ),
    ]
