# Generated by Django 3.2.3 on 2022-07-12 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FCM', '0005_fcm_game_rewinddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm_game',
            name='playersWithChatNotification',
            field=models.ManyToManyField(blank=True, related_name='playersWithChatNotificationName', to=settings.AUTH_USER_MODEL),
        ),
    ]
