# Generated by Django 3.2.3 on 2022-07-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0006_fcm_game_playerswithchatnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcm_game",
            name="kickoutDuration",
            field=models.SmallIntegerField(default=3, null=True),
        ),
    ]
