# Generated by Django 3.2.3 on 2022-07-17 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FCM', '0007_fcm_game_kickoutduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm_game',
            name='missingPlayers',
            field=models.ManyToManyField(blank=True, related_name='missingPlayersRelName', to=settings.AUTH_USER_MODEL),
        ),
    ]
