# Generated by Django 3.2.3 on 2022-07-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0008_fcm_game_missingplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm_game',
            name='player0notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fcm_game',
            name='player1notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fcm_game',
            name='player2notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fcm_game',
            name='player3notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fcm_game',
            name='player4notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fcm_game',
            name='player5notes',
            field=models.TextField(blank=True),
        ),
    ]
