# Generated by Django 3.2.3 on 2022-07-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0010_auto_20220723_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm_game',
            name='zoomLevels',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
