# Generated by Django 3.2.3 on 2022-08-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0011_fcm_game_zoomlevels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcm_game",
            name="player0currentMoveData",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="fcm_game",
            name="player1currentMoveData",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="fcm_game",
            name="player2currentMoveData",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="fcm_game",
            name="player3currentMoveData",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="fcm_game",
            name="player4currentMoveData",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="fcm_game",
            name="player5currentMoveData",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
