# Generated by Django 3.2.3 on 2022-08-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0012_auto_20220810_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm_game',
            name='rewindConsent',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
