# Generated by Django 3.2.3 on 2022-08-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0013_fcm_game_rewindconsent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcm_game",
            name="gameName",
            field=models.CharField(max_length=200),
        ),
    ]
