# Generated by Django 3.2.3 on 2022-08-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0014_alter_fcm_game_gamename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm_game',
            name='startingOptions',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
