# Generated by Django 3.2.3 on 2022-09-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0015_alter_fcm_game_startingoptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcm_game",
            name="kickoutDuration",
            field=models.SmallIntegerField(default=200, null=True),
        ),
    ]
