# Generated by Django 3.2.3 on 2022-12-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0018_auto_20220910_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm_chat',
            name='chatData',
            field=models.TextField(default='{"name":"WelcomeBot","timestamp":1670376702000,"message":"Welcome to Food Chain Magnate Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'),
        ),
    ]
