# Generated by Django 4.0.5 on 2022-12-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0019_alter_fcm_chat_chatdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcm_chat",
            name="chatData",
            field=models.TextField(
                default='{"name":"WelcomeBot","timestamp":1670427556000,"message":"Welcome to Food Chain Magnate Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'
            ),
        ),
    ]
