# Generated by Django 3.2.3 on 2022-12-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0020_alter_fcm_chat_chatdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcm_chat",
            name="chatData",
            field=models.TextField(
                default='{"name":"WelcomeBot","timestamp":1670984130000,"message":"Welcome to Food Chain Magnate Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'
            ),
        ),
        migrations.AlterField(
            model_name="fcm_game",
            name="gameName",
            field=models.CharField(max_length=120),
        ),
    ]
