# Generated by Django 3.2.3 on 2023-01-04 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("FCM", "0023_auto_20221226_0233"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcm_game",
            name="statsExcludedGame",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fcm_chat",
            name="chatData",
            field=models.TextField(
                default='{"name":"WelcomeBot","timestamp":1672816655000,"message":"Welcome to Food Chain Magnate Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'
            ),
        ),
        migrations.AlterField(
            model_name="fcm_game",
            name="phase",
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AlterField(
            model_name="fcm_game",
            name="turn",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="FCM_Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tournamentName", models.CharField(max_length=120)),
                (
                    "tournamentStatus",
                    models.CharField(
                        choices=[
                            ("OP", "Open"),
                            ("IP", "In Progress"),
                            ("FN", "Finished"),
                        ],
                        default="OP",
                        max_length=2,
                    ),
                ),
                (
                    "tournamentType",
                    models.CharField(
                        choices=[("RR", "Round Robin"), ("KO", "Knockout")],
                        default="OP",
                        max_length=2,
                    ),
                ),
                ("startingOptions", models.CharField(default="5", max_length=70)),
                ("maxTournamentPlayers", models.PositiveSmallIntegerField()),
                ("maxGamePlayers", models.PositiveSmallIntegerField()),
                ("created", models.CharField(default=1672816655000, max_length=30)),
                ("tournamentProgressionData", models.TextField(blank=True)),
                (
                    "nextRoundPlayers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="currentRoundPlayersRelName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "startingPlayers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="startingPlayersRelName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournamentWinnerRelName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fcm_game",
            name="relatedTournament",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament_relName",
                to="FCM.fcm_tournament",
            ),
        ),
    ]
