# Generated by Django 3.2.3 on 2023-01-09 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0026_auto_20230108_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm_chat',
            name='chatData',
            field=models.TextField(default='{"name":"WelcomeBot","timestamp":1673244895000,"message":"Welcome to Food Chain Magnate Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'),
        ),
        migrations.AlterField(
            model_name='fcm_game',
            name='relatedTournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_relName', to='FCM.fcm_tournament'),
        ),
        migrations.AlterField(
            model_name='fcm_tournament',
            name='created',
            field=models.CharField(default=1673244895000, max_length=30),
        ),
    ]
