# Generated by Django 3.2.3 on 2023-01-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0027_auto_20230109_0614"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcm_tournament",
            name="tournamentPointsData",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fcm_tournament",
            name="tournamentSideData",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="fcm_chat",
            name="chatData",
            field=models.TextField(
                default='{"name":"WelcomeBot","timestamp":1673670451000,"message":"Welcome to Food Chain Magnate Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'
            ),
        ),
        migrations.AlterField(
            model_name="fcm_tournament",
            name="created",
            field=models.CharField(default=1673670451000, max_length=30),
        ),
        migrations.AlterField(
            model_name="fcm_tournament",
            name="tournamentType",
            field=models.CharField(
                choices=[("RR", "Rounds"), ("KO", "Knockout"), ("TL", "Two Lives")],
                default="OP",
                max_length=2,
            ),
        ),
    ]
