# Generated by Django 3.2.3 on 2023-01-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0028_auto_20230114_0427"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcm_tournament",
            name="roundsBeforeKnockout",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="fcm_chat",
            name="chatData",
            field=models.TextField(
                default='{"name":"WelcomeBot","timestamp":1673670848000,"message":"Welcome to Food Chain Magnate Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'
            ),
        ),
        migrations.AlterField(
            model_name="fcm_tournament",
            name="created",
            field=models.CharField(default=1673670848000, max_length=30),
        ),
    ]
