# Generated by Django 3.2.3 on 2023-01-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0030_auto_20230116_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm_game',
            name='notificationSuppression',
            field=models.CharField(default='000000', max_length=30),
        ),
        migrations.AlterField(
            model_name='fcm_chat',
            name='chatData',
            field=models.TextField(default='{"name":"WelcomeBot","timestamp":1673959301000,"message":"Welcome to Food Chain Magnate Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'),
        ),
        migrations.AlterField(
            model_name='fcm_tournament',
            name='created',
            field=models.CharField(default=1673959301000, max_length=30),
        ),
    ]
