# Generated by Django 3.2.3 on 2023-01-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0031_auto_20230117_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm_game',
            name='statsExcludeConsent',
            field=models.CharField(default='00', max_length=10),
        ),
        migrations.AlterField(
            model_name='fcm_chat',
            name='chatData',
            field=models.TextField(default='{"name":"WelcomeBot","timestamp":1674106883000,"message":"Welcome to Food Chain Magnate Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'),
        ),
        migrations.AlterField(
            model_name='fcm_tournament',
            name='created',
            field=models.CharField(default=1674106883000, max_length=30),
        ),
    ]
