# Generated by Django 3.2.3 on 2023-01-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0033_auto_20230121_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm_chat',
            name='chatData',
            field=models.TextField(default='{"name":"WelcomeBot","timestamp":1674284031000,"message":"Welcome to Food Chain Magnate Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'),
        ),
        migrations.AlterField(
            model_name='fcm_tournament',
            name='created',
            field=models.CharField(default=1674284031000, max_length=30),
        ),
    ]
