# Generated by Django 3.2.3 on 2023-03-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0041_auto_20230315_0406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcm_chat",
            name="chatData",
            field=models.TextField(
                default='{"name":"WelcomeBot","timestamp":1680234135000,"message":"Welcome to Food Chain Magnate Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'
            ),
        ),
        migrations.AlterField(
            model_name="fcm_tournament",
            name="created",
            field=models.CharField(default=1680234135000, max_length=30),
        ),
    ]
