# Generated by Django 3.2.3 on 2023-12-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0051_auto_20231220_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm_chat',
            name='chatData',
            field=models.TextField(default='{"name":"WelcomeBot","timestamp":1703563511000,"message":"Welcome to Food Chain Magnate Online!=-NEWLINE-==-NEWLINE-=If you have any suggestions, questions or comments, then please do contact the webmaster at the email address in Contact (top right in the lobby). Thanks!"},'),
        ),
        migrations.AlterField(
            model_name='fcm_tournament',
            name='created',
            field=models.CharField(default=1703563511000, max_length=30),
        ),
        migrations.DeleteModel(
            name='FCM_Bug',
        ),
    ]
