# Generated by Django 3.2.3 on 2023-12-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0053_auto_20231226_0516"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcm_tournament",
            name="created",
            field=models.CharField(default=1703568468000, max_length=30),
        ),
        migrations.DeleteModel(
            name="FCM_Chat",
        ),
    ]
