# Generated by Django 3.2.3 on 2023-12-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0054_auto_20231226_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm_tournament',
            name='created',
            field=models.CharField(default=1703570502000, max_length=30),
        ),
    ]
