# Generated by Django 3.2.3 on 2023-12-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0057_alter_fcm_tournament_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcm_tournament",
            name="created",
            field=models.CharField(default=1703643330000, max_length=30),
        ),
    ]
