# Generated by Django 3.2.3 on 2023-12-30 05:13

import Lobby.sharedFunctions.sharedFunctions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0058_alter_fcm_tournament_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm_tournament',
            name='created',
            field=models.CharField(default=Lobby.sharedFunctions.sharedFunctions.SF_getTimeNow, max_length=30),
        ),
    ]
