# Generated by Django 3.2.3 on 2024-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0061_fcm_game_kickoutflexidata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm_game',
            name='gameName',
            field=models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=120),
        ),
    ]
