# Generated by Django 3.2.3 on 2024-12-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0062_alter_fcm_game_gamename'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm_game',
            name='preMoveData',
            field=models.TextField(blank=True),
        ),
    ]
