# Generated by Django 3.2.3 on 2025-04-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0065_auto_20250214_1240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcm_game",
            name="startingMap",
            field=models.CharField(blank=True, max_length=170),
        ),
    ]
