# Generated by Django 3.2.3 on 2025-05-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0066_alter_fcm_game_startingmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm_game',
            name='player0currentMoveData',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='fcm_game',
            name='player1currentMoveData',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='fcm_game',
            name='player2currentMoveData',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='fcm_game',
            name='player3currentMoveData',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='fcm_game',
            name='player4currentMoveData',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='fcm_game',
            name='player5currentMoveData',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
