# Generated by Django 3.2.3 on 2025-05-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0067_auto_20250504_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm_game',
            name='player0currentMoveData',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='fcm_game',
            name='player1currentMoveData',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='fcm_game',
            name='player2currentMoveData',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='fcm_game',
            name='player3currentMoveData',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='fcm_game',
            name='player4currentMoveData',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='fcm_game',
            name='player5currentMoveData',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
