# Generated by Django 3.2.3 on 2025-07-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0069_auto_20250513_1105"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcm_game",
            name="playersMoveData",
            field=models.TextField(blank=True),
        ),
    ]
