# Generated by Django 3.2.3 on 2025-07-11 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0070_fcm_game_playersmovedata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fcm_game",
            name="player0currentMoveData",
        ),
        migrations.RemoveField(
            model_name="fcm_game",
            name="player0currentMoveTime",
        ),
        migrations.RemoveField(
            model_name="fcm_game",
            name="player1currentMoveData",
        ),
        migrations.RemoveField(
            model_name="fcm_game",
            name="player1currentMoveTime",
        ),
        migrations.RemoveField(
            model_name="fcm_game",
            name="player2currentMoveData",
        ),
        migrations.RemoveField(
            model_name="fcm_game",
            name="player2currentMoveTime",
        ),
        migrations.RemoveField(
            model_name="fcm_game",
            name="player3currentMoveData",
        ),
        migrations.RemoveField(
            model_name="fcm_game",
            name="player3currentMoveTime",
        ),
        migrations.RemoveField(
            model_name="fcm_game",
            name="player4currentMoveData",
        ),
        migrations.RemoveField(
            model_name="fcm_game",
            name="player4currentMoveTime",
        ),
        migrations.RemoveField(
            model_name="fcm_game",
            name="player5currentMoveData",
        ),
        migrations.RemoveField(
            model_name="fcm_game",
            name="player5currentMoveTime",
        ),
    ]
