# Generated by Django 3.2.3 on 2025-08-01 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0071_auto_20250711_1136"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fcm_game",
            name="preMoveData",
        ),
    ]
