# Generated by Django 3.2.3 on 2025-08-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0072_remove_fcm_game_premovedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm_game',
            name='deleteGameVotes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
