# Generated by Django 3.2.3 on 2025-08-16 07:40

import Lobby.sharedFunctions.sharedRefs
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0074_auto_20250811_0755"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcm_game",
            name="created",
            field=models.CharField(
                default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow, max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="fcm_game",
            name="latestUpdate",
            field=models.CharField(
                default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow, max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="fcm_tournament",
            name="created",
            field=models.CharField(
                default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow, max_length=15
            ),
        ),
    ]
