# Generated by Django 5.2.7 on 2025-10-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FCM", "0076_alter_fcm_game_relatedminitournament"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcm_game",
            name="startingMap",
            field=models.CharField(blank=True, max_length=190),
        ),
    ]
