# Generated by Django 5.2.7 on 2025-11-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0077_alter_fcm_game_startingmap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcm_tournament",
            name="tournamentType",
            field=models.CharField(
                choices=[
                    ("RR", "Rounds"),
                    ("KO", "Knockout"),
                    ("TL", "Two Lives"),
                    ("PT", "Points"),
                    ("MG", "Multi Game"),
                ],
                default="RR",
                max_length=2,
            ),
        ),
    ]
