# Generated by Django 5.2.7 on 2025-12-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0078_alter_fcm_tournament_tournamenttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcm_game",
            name="gameStatus",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "AVAILABLE"),
                    ("WAITING", "WAITING"),
                    ("PRIVATE", "PRIVATE"),
                    ("ACTIVE", "ACTIVE"),
                    ("FINISHED", "FINISHED"),
                ],
                db_index=True,
                default="AVAILABLE",
                max_length=9,
            ),
        ),
    ]
