# Generated by Django 5.2.9 on 2026-01-13 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0082_fcmminitournament"),
        ("Lobby", "0055_alter_main_tournament_gamecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcm_game",
            name="relatedMainTournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintournamentFCM_relName",
                to="Lobby.main_tournament",
            ),
        ),
    ]
