# Generated by Django 5.2.9 on 2026-01-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0083_fcm_game_relatedmaintournament"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcm_game",
            name="phase",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
