# Generated by Django 5.2.9 on 2026-01-14 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0088_alter_fcm_game_statsexcludeconsent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fcm_game",
            old_name="seatOffset",
            new_name="playerOrderSeed",
        ),
    ]
