# Generated by Django 5.2.9 on 2026-01-23 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0090_fcm_game_activevotes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fcm_game",
            name="rewindConsent",
        ),
    ]
