# Generated by Django 5.2.9 on 2026-02-12 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0092_fcm_game_automoves"),
        ("Lobby", "0082_migrate_fcm_games"),
    ]

    operations = [
        migrations.CreateModel(
            name="FCMgame",
            fields=[],
            options={
                "verbose_name": "FCM_Game",
                "verbose_name_plural": "FCM_Games",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Lobby.game",),
        ),
    ]
