# Generated by Django 5.2.9 on 2026-02-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FCM', '0093_fcmgame'),
        ('Lobby', '0083_remove_game_relatedfcmtournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcm_game',
            name='relatedTournament',
        ),
        migrations.DeleteModel(
            name='FCM_Tournament',
        ),
    ]
