# Generated by Django 5.2.9 on 2026-02-17 01:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FCM", "0094_remove_fcm_game_relatedtournament_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FCM_Game",
        ),
    ]
