# Generated by Django 5.2.9 on 2025-12-14 10:11

import Lobby.sharedFunctions.sharedRefs
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNS_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=120)),
                ('gameDescription', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=120)),
                ('gameStatus', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('WAITING', 'WAITING'), ('PRIVATE', 'PRIVATE'), ('ACTIVE', 'ACTIVE'), ('FINISHED', 'FINISHED')], db_index=True, default='AVAILABLE', max_length=9)),
                ('latestUpdate', models.CharField(default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow, max_length=15)),
                ('startingOptions', models.CharField(blank=True, max_length=20)),
                ('currentPlayers', models.CharField(blank=True, max_length=100)),
                ('playerOrderSeed', models.PositiveSmallIntegerField(default=0)),
                ('maxPlayers', models.PositiveSmallIntegerField(default=2)),
                ('turn', models.PositiveSmallIntegerField(default=1)),
                ('phase', models.PositiveSmallIntegerField(default=0)),
                ('kickoutDuration', models.PositiveSmallIntegerField(default=200)),
                ('gamePace', models.PositiveSmallIntegerField(default=40)),
                ('created', models.CharField(default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow, max_length=15)),
                ('zoomLevels', models.CharField(default='[24, 24, 24, 24]', max_length=30)),
                ('statsExcludeConsent', models.CharField(default='0000', max_length=4)),
                ('chatData', models.TextField(blank=True)),
                ('player0notes', models.TextField(blank=True)),
                ('player1notes', models.TextField(blank=True)),
                ('player2notes', models.TextField(blank=True)),
                ('player3notes', models.TextField(blank=True)),
                ('gameData', models.TextField(blank=True)),
                ('rewindData', models.TextField(blank=True)),
                ('rewindTempData', models.TextField(blank=True)),
                ('statsExcludedGame', models.BooleanField(default=False)),
                ('kickoutFlexiData', models.TextField(blank=True)),
            ],
        ),
    ]
