# Generated by Django 5.2.9 on 2026-10-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CNS', '0001_initial'),
        ('Lobby', '0116_tournament_startingmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNSMainTournament',
            fields=[
            ],
            options={
                'verbose_name': 'CNS Main Tournament',
                'verbose_name_plural': 'CNS Main Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
        migrations.CreateModel(
            name='CNSMiniTournament',
            fields=[
            ],
            options={
                'verbose_name': 'CNS Mini Tournament',
                'verbose_name_plural': 'CNS Mini Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
    ]
