# Generated by Django 5.2.9 on 2025-12-14 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CNS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cns_game',
            name='allPlayers',
            field=models.ManyToManyField(related_name='CNSallPlayersRelName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cns_game',
            name='creator',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CNSgame_creator_relName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cns_game',
            name='host',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CNSgame_host_relName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cns_game',
            name='invitedPlayers',
            field=models.ManyToManyField(blank=True, related_name='CNSinvitedPlayersRelName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cns_game',
            name='kickedPlayers',
            field=models.ManyToManyField(blank=True, related_name='CNSkickedPlayersRelName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cns_game',
            name='missingPlayers',
            field=models.ManyToManyField(blank=True, related_name='CNSmissingPlayersRelName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cns_game',
            name='playersWithChatNotification',
            field=models.ManyToManyField(blank=True, related_name='CNSplayersWithChatNotificationName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cns_game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CNSgame_winner_relName', to=settings.AUTH_USER_MODEL),
        ),
    ]
