# Generated by Django 3.2.3 on 2024-03-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CNS", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cns_game",
            name="phase",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cns_game",
            name="turn",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
