# Generated by Django 5.2.7 on 2025-12-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CNS", "0006_alter_cns_game_creator_alter_cns_game_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cns_game",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
