# Generated by Django 5.2.7 on 2025-12-18 14:39

import Lobby.sharedFunctions.sharedRefs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CNS", "0007_alter_cns_game_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cns_game",
            name="latestUpdate",
            field=models.CharField(
                db_index=True,
                default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow,
                max_length=15,
            ),
        ),
    ]
