# Generated by Django 5.2.9 on 2026-01-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNS', '0008_alter_cns_game_latestupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cns_game',
            name='turn',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
