# Generated by Django 5.2.9 on 2026-01-23 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CNS", "0014_cns_game_activevotes"),
        ("Lobby", "0062_game_relatedmaintournament_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CNSgame",
            fields=[],
            options={
                "verbose_name": "CNS_Game",
                "verbose_name_plural": "CNS_Games",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Lobby.game",),
        ),
    ]
