# Generated by Django 5.2.9 on 2026-02-04 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CNS", "0016_cns_game_automoves"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CNS_Game",
        ),
    ]
