# Generated by Django 3.2.3 on 2025-03-04 06:10

import Lobby.sharedFunctions.sharedFunctions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KFW_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=120)),
                ('gameDescription', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=120)),
                ('gameStatus', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('WAITING', 'WAITING'), ('PRIVATE', 'PRIVATE'), ('ACTIVE', 'ACTIVE'), ('FINISHED', 'FINISHED')], default='AVAILABLE', max_length=9)),
                ('latestUpdate', models.CharField(default=Lobby.sharedFunctions.sharedFunctions.SF_getTimeNow, max_length=15)),
                ('startingOptions', models.CharField(blank=True, max_length=20)),
                ('currentPlayers', models.CharField(blank=True, max_length=100)),
                ('playerOrderSeed', models.PositiveSmallIntegerField(default=0)),
                ('maxPlayers', models.PositiveSmallIntegerField(default=2)),
                ('turn', models.PositiveSmallIntegerField(default=1)),
                ('phase', models.PositiveSmallIntegerField(default=0)),
                ('kickoutDuration', models.PositiveSmallIntegerField(default=200)),
                ('gamePace', models.PositiveSmallIntegerField(default=40)),
                ('created', models.CharField(default=Lobby.sharedFunctions.sharedFunctions.SF_getTimeNow, max_length=15)),
                ('zoomLevels', models.CharField(default='[]', max_length=30)),
                ('chatData', models.TextField(blank=True)),
                ('player0notes', models.TextField(blank=True)),
                ('player1notes', models.TextField(blank=True)),
                ('player2notes', models.TextField(blank=True)),
                ('player3notes', models.TextField(blank=True)),
                ('player4notes', models.TextField(blank=True)),
                ('player5notes', models.TextField(blank=True)),
                ('gameData', models.TextField(blank=True)),
                ('rewindData', models.TextField(blank=True)),
                ('rewindTempData', models.TextField(blank=True)),
                ('tournamentGame', models.BooleanField(default=False)),
                ('statsExcludedGame', models.BooleanField(default=False)),
                ('kickoutFlexiData', models.TextField(blank=True)),
                ('allPlayers', models.ManyToManyField(related_name='KFWallPlayersRelName', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='KFWgame_creator_relName', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='KFWgame_host_relName', to=settings.AUTH_USER_MODEL)),
                ('invitedPlayers', models.ManyToManyField(blank=True, related_name='KFWinvitedPlayersRelName', to=settings.AUTH_USER_MODEL)),
                ('kickedPlayers', models.ManyToManyField(blank=True, related_name='KFWkickedPlayersRelName', to=settings.AUTH_USER_MODEL)),
                ('missingPlayers', models.ManyToManyField(blank=True, related_name='KFWmissingPlayersRelName', to=settings.AUTH_USER_MODEL)),
                ('playersWithChatNotification', models.ManyToManyField(blank=True, related_name='KFWplayersWithChatNotificationName', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ManyToManyField(blank=True, related_name='KFWgame_winner_relName', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
