# Generated by Django 5.2.9 on 2026-10-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KFW', '0001_initial'),
        ('Lobby', '0116_tournament_startingmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='KFWMainTournament',
            fields=[
            ],
            options={
                'verbose_name': 'KFW Main Tournament',
                'verbose_name_plural': 'KFW Main Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
        migrations.CreateModel(
            name='KFWMiniTournament',
            fields=[
            ],
            options={
                'verbose_name': 'KFW Mini Tournament',
                'verbose_name_plural': 'KFW Mini Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
    ]
