# Generated by Django 3.2.3 on 2025-06-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("KFW", "0002_auto_20250506_0833"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kfw_game",
            name="serverData",
            field=models.TextField(
                blank=True, default="[[40, 40, 40, 0], [16, 16, 16]]"
            ),
        ),
    ]
