# Generated by Django 5.2.9 on 2026-01-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("KFW", "0007_alter_kfw_game_latestupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kfw_game",
            name="turn",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
