# Generated by Django 5.2.9 on 2026-01-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KFW', '0008_alter_kfw_game_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kfw_game',
            name='gamePace',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='kfw_game',
            name='startingOptions',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
