# Generated by Django 5.2.9 on 2026-01-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("KFW", "0009_alter_kfw_game_gamepace_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kfw_game",
            name="deleteGameVotes",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
