# Generated by Django 5.2.9 on 2026-02-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("KFW", "0014_kfw_game_automoves"),
    ]

    operations = [
        migrations.AddField(
            model_name="kfw_game",
            name="gameDataBLOB",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
