# Generated by Django 5.2.9 on 2026-02-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KFW', '0015_kfw_game_gamedatablob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kfw_game',
            name='deleteGameVotes',
        ),
        migrations.RemoveField(
            model_name='kfw_game',
            name='statsExcludeConsent',
        ),
    ]
