# Generated by Django 5.2.9 on 2026-02-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KFW', '0017_kfwgame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KFW_Game',
        ),
    ]
