# Generated from ./RNB/vueRNB/src/js/RNBreference.js
# Total blocks synced: 1
PHASE_CONFLICT_PRODUCTION_DECISION = 0
PHASE_CONFLICT_PRODUCTION_PRAYING = 1
PHASE_CONFLICT_PRODUCTION_TURN_ORDER = 2
PHASE_PRODUCTION_TO = 3
PHASE_CONFLICT_MOVEMENT_DECISION = 4
PHASE_CONFLICT_MOVEMENT_PRAYING = 5
PHASE_CONFLICT_MOVEMENT_TURN_ORDER = 6
PHASE_MOVEMENT_TO = 7
PHASE_CONFLICT_BUILDING_DECISION = 8
PHASE_CONFLICT_BUILDING_PRAYING = 9
PHASE_CONFLICT_BUILDING_TURN_ORDER = 10
PHASE_BUILDING_TO = 11
PHASE_CONFLICT_WONDER_DECISION = 12
PHASE_CONFLICT_WONDER_PRAYING = 13
PHASE_CONFLICT_WONDER_TURN_ORDER = 14
PHASE_WONDER_TO = 15
MAX_PHASE_REACHED = 16
PHASE_GAME_OVER = 19
