# Generated from ./RNB/vueRNB/src/js/RNBreference.js
# Total blocks synced: 2
SO_BASE_GAME = -1
SO_ELECTRICITY = 0
SO_MANAGEMENT = 1
SO_ART = 2
SO_TRADE = 3
SO_POLDER = 4
SO_CITY = 5
SO_JUMP_START = 6
SO_FUNDAMENTAL_RESEARCH = 7
SO_PLANES = 8
SO_TRAINS = 9
SO_BOMBS = 10
PHASE_CONFLICT_PRODUCTION_DECISION = 0
PHASE_CONFLICT_PRODUCTION_PRAYING = 1
PHASE_CONFLICT_PRODUCTION_TURN_ORDER = 2
PHASE_PRODUCTION_TO = 3
PHASE_CONFLICT_MOVEMENT_DECISION = 4
PHASE_CONFLICT_MOVEMENT_PRAYING = 5
PHASE_CONFLICT_MOVEMENT_TURN_ORDER = 6
PHASE_MOVEMENT_TO = 7
PHASE_CONFLICT_BUILDING_DECISION = 8
PHASE_CONFLICT_BUILDING_PRAYING = 9
PHASE_CONFLICT_BUILDING_TURN_ORDER = 10
PHASE_BUILDING_TO = 11
PHASE_CONFLICT_WONDER_DECISION = 12
PHASE_CONFLICT_WONDER_PRAYING = 13
PHASE_CONFLICT_WONDER_TURN_ORDER = 14
PHASE_WONDER_TO = 15
MAX_PHASE_REACHED = 16
PHASE_LOOKBACK_AMOUNT = 2
PHASE_GAME_OVER = 19
PHASE_PRODUCTIONS = [PHASE_PRODUCTION_TO]
PHASE_MOVEMENTS = [PHASE_MOVEMENT_TO]
PHASE_BUILDINGS = [PHASE_BUILDING_TO]
PHASE_WONDERS = [PHASE_WONDER_TO]
MAIN_PHASES = [
    PHASE_PRODUCTION_TO,
    PHASE_MOVEMENT_TO,
    PHASE_BUILDING_TO,
    PHASE_WONDER_TO,
]
PHASE_CONFLICT_PRODUCTIONS = [
    PHASE_CONFLICT_PRODUCTION_DECISION,
    PHASE_CONFLICT_PRODUCTION_PRAYING,
    PHASE_CONFLICT_PRODUCTION_TURN_ORDER,
]
PHASE_CONFLICT_MOVEMENTS = [
    PHASE_CONFLICT_MOVEMENT_DECISION,
    PHASE_CONFLICT_MOVEMENT_PRAYING,
    PHASE_CONFLICT_MOVEMENT_TURN_ORDER,
]
PHASE_CONFLICT_BUILDINGS = [
    PHASE_CONFLICT_BUILDING_DECISION,
    PHASE_CONFLICT_BUILDING_PRAYING,
    PHASE_CONFLICT_BUILDING_TURN_ORDER,
]
PHASE_CONFLICT_WONDERS = [
    PHASE_CONFLICT_WONDER_DECISION,
    PHASE_CONFLICT_WONDER_PRAYING,
    PHASE_CONFLICT_WONDER_TURN_ORDER,
]
PHASE_CONFLICT_DECISIONS = [
    PHASE_CONFLICT_PRODUCTION_DECISION,
    PHASE_CONFLICT_MOVEMENT_DECISION,
    PHASE_CONFLICT_BUILDING_DECISION,
    PHASE_CONFLICT_WONDER_DECISION,
]
PHASE_CONFLICT_PRAYINGS = [
    PHASE_CONFLICT_PRODUCTION_PRAYING,
    PHASE_CONFLICT_MOVEMENT_PRAYING,
    PHASE_CONFLICT_BUILDING_PRAYING,
    PHASE_CONFLICT_WONDER_PRAYING,
]
PHASE_CONFLICT_TURN_ORDERS = [
    PHASE_CONFLICT_PRODUCTION_TURN_ORDER,
    PHASE_CONFLICT_MOVEMENT_TURN_ORDER,
    PHASE_CONFLICT_BUILDING_TURN_ORDER,
    PHASE_CONFLICT_WONDER_TURN_ORDER,
]
ALL_PHASE_CONFLICTS = [
    PHASE_CONFLICT_PRODUCTION_DECISION,
    PHASE_CONFLICT_PRODUCTION_PRAYING,
    PHASE_CONFLICT_PRODUCTION_TURN_ORDER,
    PHASE_CONFLICT_MOVEMENT_DECISION,
    PHASE_CONFLICT_MOVEMENT_PRAYING,
    PHASE_CONFLICT_MOVEMENT_TURN_ORDER,
    PHASE_CONFLICT_BUILDING_DECISION,
    PHASE_CONFLICT_BUILDING_PRAYING,
    PHASE_CONFLICT_BUILDING_TURN_ORDER,
    PHASE_CONFLICT_WONDER_DECISION,
    PHASE_CONFLICT_WONDER_PRAYING,
    PHASE_CONFLICT_WONDER_TURN_ORDER,
]
ALL_PHASE_CONFLICT_DECISIONS = [
    PHASE_CONFLICT_PRODUCTION_DECISION,
    PHASE_CONFLICT_MOVEMENT_DECISION,
    PHASE_CONFLICT_BUILDING_DECISION,
    PHASE_CONFLICT_WONDER_DECISION,
]
