# Generated by Django 5.2.9 on 2026-04-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HLC', '0001_initial'),
        ('Lobby', '0107_profile_preferredrnboptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HLCMainTournament',
            fields=[
            ],
            options={
                'verbose_name': 'HLC Main Tournament',
                'verbose_name_plural': 'HLC Main Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
        migrations.CreateModel(
            name='HLCMiniTournament',
            fields=[
            ],
            options={
                'verbose_name': 'HLC Mini Tournament',
                'verbose_name_plural': 'HLC Mini Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
    ]
