"""
Django settings for OnlineBoardGamers project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from decouple import config, Csv
import os
from os.path import join
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)
LOCAL_USER = config("LOCAL_USER", default=False, cast=bool)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if DEBUG or LOCAL_USER:
    SECRET_KEY = config("SEECRET_KEY_HOME_SERVER")
else:
    SECRET_KEY = config("SECRET_KEY_PRODUCTION")

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60

if not DEBUG:
    SECURE_SSL_REDIRECT = False  # Handled by cloudflare

    CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = []
    USE_X_FORWARDED_HOST = False

    SESSION_ENGINE = (
        "django.contrib.sessions.backends.db"  # Or cached_db, or file, etc.
    )
    SESSION_COOKIE_SECURE = (
        True  # Only send the session cookie over HTTPS in production
    )
    SESSION_COOKIE_HTTPONLY = (
        True  # Prevents JavaScript from accessing the session cookie
    )
    SESSION_COOKIE_SAMESITE = "Lax"  # Or 'Strict', depending on your needs

    SECURE_HSTS_SECONDS = 60
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

LOGIN_URL = "myLogin"

if LOCAL_USER and DEBUG:
    ALLOWED_HOSTS = ["localhost", "192.168.1.2"]
else:
    # ALLOWED_HOSTS = ['pythonanywhere']
    ALLOWED_HOSTS = ["www.onlineboardgamers.com", "onlineboardgamers.com"]

if LOCAL_USER:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_USE_TLS = True
    EMAIL_PORT = 587
    EMAIL_HOST_USER = "OnlineBoardGamers@gmail.com"
    EMAIL_HOST_PASSWORD = config("OBG_EMAIL_APP_PWD")


EMAIL_HOST_USER_TURN = []
EMAIL_HOST_PASSWORD_TURN = []

# Application definition

AUTH_USER_MODEL = "Lobby.User"
CSRF_FAILURE_VIEW = "Lobby.views.csrf_failure"

SITE_ID = 1

INSTALLED_APPS = [
    # 'FCM.apps.FCMConfig',
    # 'Lobby.apps.LobbyConfig',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "dal",
    "dal_select2",
    "FCM",
    "Lobby",
    "user_visit",
    "Bus",
    "HC",
    "TGZ",
    "CNS",
    "AQY",
    "IND",
    "KFW",
    "PPF",
    "WEB",
    "RNB",
    "statici18n",
    "i18n",
]

APPEND_SLASH = True

MIDDLEWARE = [
    "Lobby.middleware.ForceTrailingSlashMiddleware",
    # This MUST come first
    "django.middleware.security.SecurityMiddleware",
    # This must come before Authentication and CsrfView
    "django.contrib.sessions.middleware.SessionMiddleware",
    # This must come after Session and Authentication
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    # This must come before AuthenticationM, and any permissions middleware
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "user_visit.middleware.UserVisitMiddleware",
]

ROOT_URLCONF = "OnlineBoardGamers.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
            ],
        },
    },
]

WSGI_APPLICATION = "OnlineBoardGamers.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


# if os.environ["DJANGO_DEBUG"] == True:
if LOCAL_USER:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": config("LOCAL_DB_NAME"),
            "USER": config("LOCAL_DB_USER"),
            "PASSWORD": config("LOCAL_DB_PWD"),
            "HOST": config("LOCAL_DB_HOST"),
            "PORT": "3306",
            "OPTIONS": {
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
                "charset": "utf8mb4",
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": "OnlineGaming$default",
            "USER": "OnlineGaming",
            "PASSWORD": config("PRODUCTION_DB_PWD"),
            "HOST": "OnlineGaming.mysql.pythonanywhere-services.com",
            "OPTIONS": {
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
                "charset": "utf8mb4",
            },
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#    {
#        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#    },
#    {
# 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#   },
# {
#       'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#   },
# ]

AUTH_PASSWORD_VALIDATORS = [
    # {
    #    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 5,
        },
    },
    # {
    #    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

if DEBUG or LOCAL_USER:
    LANGUAGES = (
        ("en-gb", "English (United Kingdom)"),
        # ("zh-hans", gettext_noop("Simplified Chinese")),
        # ("zh-hans", "Simplified Chinese"),
        ("zh-hans", "简体中文"),
        ("es", "Spanish (Spain)"),
        ("de", "Deutsche"),
        # ('es', 'Spanish (Spain)'),
    )
else:
    LANGUAGES = (
        ("en-gb", "English (United Kingdom)"),
        ("zh-hans", "简体中文"),
    )


LANGUAGE_CODE = "en-gb"

LOCALE_PATHS = [
    join(BASE_DIR, "Lobby", "locale"),
    join(BASE_DIR, "FCM", "locale"),
    join(BASE_DIR, "HC", "locale"),
]

# TIME_ZONE = 'Asia/Hong_Kong'
TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# ── STATIC FILES  ──────────────────
STATIC_URL = "/static/"

# Source files (where Lobby/profile.js lives)
STATICFILES_DIRS = []

# Output folder for collectstatic (separate from source!)
STATIC_ROOT = os.path.join(
    BASE_DIR, "staticfiles"
)  # → /home/OnlineGaming/.virtualenvs/OnlineGaming/staticfiles/


STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Update this line (assuming custom_storage.py is in your root)
        #"BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
        "BACKEND": "custom_storage.SafeManifestStaticFilesStorage",
    },
}


# Keep i18n if needed
if DEBUG or LOCAL_USER:
    STATICI18N_ROOT = BASE_DIR / "i18n" / "static"

# Where ViteJS assets are built.
# DJANGO_VITE_ASSETS_PATH = BASE_DIR / "static" / "dist"

# If use HMR or not.
# DJANGO_VITE_DEV_MODE = DEBUG

# Name of static files folder (after called python manage.py collectstatic)
# SEE ABOVE
# STATIC_ROOT = BASE_DIR / "static"

# Include DJANGO_VITE_ASSETS_PATH into STATICFILES_DIRS to be copied inside
# when run command python manage.py collectstatic
# STATICFILES_DIRS = [DJANGO_VITE_ASSETS_PATH]


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOG_DIR = os.path.join(BASE_DIR, "logs")

# Ensure log directory exists
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "file": {
            "level": "DEBUG",  # Or logging.INFO
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "custom_debug2.log"),
            "formatter": "standard",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        #"django.db.backends": {
        #    "level": "DEBUG",
        #},
        "Lobby.views": {
            "handlers": ["file", "console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "FCM.models": {
            "handlers": ["file", "console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "FCM.admin": {
            "handlers": ["file", "console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "Lobby.middleware": {  # Add this for DebugSlashMiddleware
            "handlers": ["file", "console"],
            "level": "DEBUG",
            "propagate": False,  # Prevent propagation to root logger
        },
        "Lobby.utils": {
            "handlers": ["file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
    },
}
