# Generated by Django 5.2.9 on 2026-09-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lobby', '0115_alter_game_gamecode_alter_tournament_gamecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDLgame',
            fields=[
            ],
            options={
                'verbose_name': 'DDL_Game',
                'verbose_name_plural': 'DDL_Games',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.game',),
        ),
    ]
