# Generated by Django 5.2.9 on 2025-12-14 10:11

import Lobby.models
import Lobby.sharedFunctions.sharedRefs
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.CharField(max_length=120)),
                ('timestamp', models.CharField(default=Lobby.models.get_default_timestamp, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendEmailNotificationOnTurn', models.BooleanField(default=True)),
                ('emailNotifications', models.CharField(default='[1,1,1,1,1,1,1,1,1,1,1]', max_length=40)),
                ('stopEmailsUntil', models.PositiveIntegerField(blank=True, null=True)),
                ('webhooks', models.TextField(blank=True, null=True)),
                ('preferredRestaurantColour', models.SmallIntegerField(default=-1)),
                ('highContrastBoardItems', models.BooleanField(default=False)),
                ('preferredHCcolour', models.SmallIntegerField(default=-1)),
                ('preferredBusColour', models.SmallIntegerField(default=-1)),
                ('preferredBusBoard', models.SmallIntegerField(default=0)),
                ('preferredTGZcolour', models.SmallIntegerField(default=-1)),
                ('TGZminimalText', models.BooleanField(default=False)),
                ('preferredCNScolour', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('preferredAQYoptions', models.CharField(blank=True, max_length=30)),
                ('preferredINDoptions', models.CharField(blank=True, max_length=30)),
                ('preferredKFWoptions', models.CharField(blank=True, max_length=30)),
                ('preferredWEBoptions', models.CharField(blank=True, max_length=30)),
                ('FCMtournamentTrophies', models.CharField(default='[[0,0,0,0,0]]', max_length=100)),
                ('liveNotification', models.SmallIntegerField(default=1, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('showAssistance', models.BooleanField(default=True)),
                ('profileLanguage', models.CharField(choices=[('en-gb', 'English (United Kingdom)'), ('zh-hans', '简体中文'), ('es', 'Spanish (Spain)'), ('de', 'Deutsche')], default='en-gb', max_length=10)),
                ('blacklistedPlayers', models.ManyToManyField(blank=True, related_name='blacklistedPlayers_relName', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mini_Tournaments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gameCode', models.CharField(choices=[('FCM', 'Food Chain Magnate'), ('HC', 'Horseless Carriage'), ('TGZ', 'The Great Zimbabwe'), ('CNS', 'Cannes'), ('AQY', 'Antiquity'), ('IND', 'Indonesia'), ('KFW', 'Keyflower')], default='FCM', max_length=3)),
                ('tournamentName', models.CharField(max_length=120)),
                ('tournamentDescription', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=120)),
                ('tournamentStatus', models.CharField(choices=[('OP', 'Open'), ('PR', 'Private'), ('IP', 'In Progress'), ('FN', 'Finished')], default='OP', max_length=2)),
                ('tournamentType', models.CharField(choices=[('RR', 'Rounds'), ('KO', 'Knockout'), ('TL', 'Two Lives'), ('PT', 'Points'), ('MG', 'Multi Game')], default='RR', max_length=2)),
                ('startingOptions', models.CharField(blank=True, default='', max_length=80)),
                ('maxTournamentPlayers', models.PositiveSmallIntegerField()),
                ('maxGamePlayers', models.PositiveSmallIntegerField()),
                ('roundsBeforeKnockout', models.PositiveSmallIntegerField(default=4)),
                ('winnersData', models.TextField(blank=True)),
                ('created', models.CharField(default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow, max_length=15)),
                ('tournamentProgressionData', models.TextField(blank=True)),
                ('tournamentSideData', models.TextField(blank=True)),
                ('tournamentPointsData', models.TextField(blank=True)),
                ('chatData', models.TextField(blank=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MT_creator_relName', to=settings.AUTH_USER_MODEL)),
                ('invitedPlayers', models.ManyToManyField(blank=True, related_name='invitedPlayersRelName_MT', to=settings.AUTH_USER_MODEL)),
                ('nextRoundPlayers', models.ManyToManyField(blank=True, related_name='currentRoundPlayersRelName_MT', to=settings.AUTH_USER_MODEL)),
                ('startingPlayers', models.ManyToManyField(blank=True, related_name='startingPlayersRelName_MT', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gameCode', models.CharField(choices=[('FCM', 'Food Chain Magnate'), ('HC', 'Horseless Carriage'), ('TGZ', 'The Great Zimbabwe'), ('CNS', 'Cannes'), ('AQY', 'Antiquity'), ('IND', 'Indonesia'), ('KFW', 'Keyflower')], default='FCM', max_length=3)),
                ('tournamentName', models.CharField(max_length=120)),
                ('tournamentDescription', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=120)),
                ('tournamentStatus', models.CharField(choices=[('OP', 'Open'), ('PR', 'Private'), ('IP', 'In Progress'), ('FN', 'Finished')], default='OP', max_length=2)),
                ('tournamentType', models.CharField(choices=[('RR', 'Rounds'), ('KO', 'Knockout'), ('TL', 'Two Lives'), ('PT', 'Points'), ('MG', 'Multi Game')], default='RR', max_length=2)),
                ('startingOptions', models.CharField(blank=True, default='', max_length=80)),
                ('maxTournamentPlayers', models.PositiveSmallIntegerField()),
                ('maxGamePlayers', models.PositiveSmallIntegerField()),
                ('roundsBeforeKnockout', models.PositiveSmallIntegerField(default=4)),
                ('winnersData', models.TextField(blank=True)),
                ('created', models.CharField(default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow, max_length=15)),
                ('tournamentProgressionData', models.TextField(blank=True)),
                ('tournamentSideData', models.TextField(blank=True)),
                ('tournamentPointsData', models.TextField(blank=True)),
                ('chatData', models.TextField(blank=True)),
                ('nextRoundPlayers', models.ManyToManyField(blank=True, related_name='currentRoundPlayersRelName_MainT', to=settings.AUTH_USER_MODEL)),
                ('startingPlayers', models.ManyToManyField(blank=True, related_name='startingPlayersRelName_MainT', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
