# Generated by Django 3.2.3 on 2022-06-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='showAssistance',
            field=models.BooleanField(default=True),
        ),
    ]
