# Generated by Django 3.2.3 on 2022-07-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0002_profile_showassistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferredRestaurantColour',
            field=models.SmallIntegerField(default=-1, null=True),
        ),
    ]
