# Generated by Django 3.2.3 on 2022-07-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0003_alter_profile_preferredrestaurantcolour'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liveNotification',
            field=models.SmallIntegerField(default=1, null=True),
        ),
    ]
