# Generated by Django 4.0.5 on 2022-12-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0005_auto_20221207_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sendSlackWebhookNotificationOnTurn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='slackWebhookURL',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
