# Generated by Django 3.2.3 on 2023-01-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0006_profile_sendslackwebhooknotificationonturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='highContrastBoardItems',
            field=models.BooleanField(default=False),
        ),
    ]
