# Generated by Django 3.2.3 on 2023-01-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0007_profile_highcontrastboarditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='FCMtournamentTrophies',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
