# Generated by Django 3.2.3 on 2023-02-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0008_profile_fcmtournamenttrophies'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferredHCcolour',
            field=models.SmallIntegerField(default=-1, null=True),
        ),
    ]
