# Generated by Django 3.2.3 on 2023-03-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0009_profile_preferredhccolour"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="discordWebhookUserID",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
