# Generated by Django 3.2.3 on 2023-09-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0015_alter_changelog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='timestamp',
            field=models.CharField(default=1695471951000, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sendEmailNotificationOnTurn',
            field=models.BooleanField(default=True),
        ),
    ]
