# Generated by Django 3.2.3 on 2023-10-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0017_auto_20231003_1037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="timestamp",
            field=models.CharField(default=1696344953000, max_length=30),
        ),
    ]
