# Generated by Django 3.2.3 on 2023-12-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0020_auto_20231219_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='timestamp',
            field=models.CharField(default=1703041490000, max_length=30),
        ),
    ]
