# Generated by Django 3.2.3 on 2023-12-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0021_alter_changelog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='timestamp',
            field=models.CharField(default=1703563511000, max_length=30),
        ),
    ]
