# Generated by Django 3.2.3 on 2023-12-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0022_alter_changelog_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="timestamp",
            field=models.CharField(default=1703567803000, max_length=30),
        ),
    ]
