# Generated by Django 3.2.3 on 2023-12-30 05:13

import Lobby.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0028_auto_20231227_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='timestamp',
            field=models.CharField(default="TEMP_PLACEHOLDER", max_length=30),
        ),
    ]
