# Generated by Django 3.2.3 on 2024-02-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0029_alter_changelog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='TGZminimalText',
            field=models.BooleanField(default=False),
        ),
    ]
