# Generated by Django 3.2.3 on 2024-04-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0030_profile_tgzminimaltext"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferredCNScolour",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
