# Generated by Django 3.2.3 on 2024-06-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0031_profile_preferredcnscolour'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferredAQYoptions',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
