# Generated by Django 3.2.3 on 2024-11-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0032_profile_preferredaqyoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferredINDoptions',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
