# Generated by Django 3.2.3 on 2024-12-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0033_profile_preferredindoptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stopEmailsUntil",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
