# Generated by Django 3.2.3 on 2025-01-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0034_profile_stopemailsuntil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="stopEmailsUntil",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
