# Generated by Django 3.2.3 on 2025-01-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0035_alter_profile_stopemailsuntil"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="webhooks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
