# Generated by Django 3.2.3 on 2025-02-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0036_profile_webhooks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="discordWebhookURL",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="discordWebhookUserID",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="sendDiscordWebhookNotificationOnTurn",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="sendSlackWebhookNotificationOnTurn",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="slackWebhookURL",
        ),
        migrations.AddField(
            model_name="profile",
            name="emailNotifications",
            field=models.CharField(
                default="[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]", max_length=40
            ),
        ),
    ]
