# Generated by Django 3.2.3 on 2025-03-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0037_auto_20250214_1240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="emailNotifications",
            field=models.CharField(
                default="[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]", max_length=40
            ),
        ),
    ]
