# Generated by Django 3.2.3 on 2025-03-30 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0038_alter_profile_emailnotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blacklistedPlayers',
            field=models.ManyToManyField(blank=True, related_name='blacklistedPlayers_relName', to=settings.AUTH_USER_MODEL),
        ),
    ]
