# Generated by Django 3.2.3 on 2025-05-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0039_profile_blacklistedplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferredKFWoptions',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='FCMtournamentTrophies',
            field=models.CharField(default='[[0,0,0,0,0]]', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emailNotifications',
            field=models.CharField(default='[1,1,1,1,1,1,1,1,1,1,1]', max_length=40),
        ),
    ]
