# Generated by Django 3.2.3 on 2025-08-16 07:40

import Lobby.sharedFunctions.sharedRefs
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0044_mini_tournaments_invitedplayers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mini_tournaments",
            name="created",
            field=models.CharField(
                default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow, max_length=15
            ),
        ),
    ]
