# Generated by Django 3.2.3 on 2025-08-20 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0045_alter_mini_tournaments_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="mini_tournaments",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="MT_creator_relName",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
