# Generated by Django 3.2.3 on 2025-09-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0046_mini_tournaments_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferredWEBoptions",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
