# Generated by Django 5.2.7 on 2025-11-23 15:14

import Lobby.sharedFunctions.sharedRefs
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0047_profile_preferredweboptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mini_tournaments",
            name="tournamentType",
            field=models.CharField(
                choices=[
                    ("RR", "Rounds"),
                    ("KO", "Knockout"),
                    ("TL", "Two Lives"),
                    ("PT", "Points"),
                    ("MG", "Multi Game"),
                ],
                default="RR",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="Main_Tournaments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gameCode",
                    models.CharField(
                        choices=[
                            ("FCM", "Food Chain Magnate"),
                            ("HC", "Horseless Carriage"),
                            ("TGZ", "The Great Zimbabwe"),
                            ("CNS", "Cannes"),
                            ("AQY", "Antiquity"),
                            ("IND", "Indonesia"),
                            ("KFW", "Keyflower"),
                        ],
                        default="FCM",
                        max_length=3,
                    ),
                ),
                ("tournamentName", models.CharField(max_length=120)),
                (
                    "tournamentDescription",
                    models.CharField(
                        blank=True, max_length=120
                    ),
                ),
                (
                    "tournamentStatus",
                    models.CharField(
                        choices=[
                            ("OP", "Open"),
                            ("PR", "Private"),
                            ("IP", "In Progress"),
                            ("FN", "Finished"),
                        ],
                        default="OP",
                        max_length=2,
                    ),
                ),
                (
                    "tournamentType",
                    models.CharField(
                        choices=[
                            ("RR", "Rounds"),
                            ("KO", "Knockout"),
                            ("TL", "Two Lives"),
                            ("PT", "Points"),
                            ("MG", "Multi Game"),
                        ],
                        default="RR",
                        max_length=2,
                    ),
                ),
                (
                    "startingOptions",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("maxTournamentPlayers", models.PositiveSmallIntegerField()),
                ("maxGamePlayers", models.PositiveSmallIntegerField()),
                ("roundsBeforeKnockout", models.PositiveSmallIntegerField(default=4)),
                ("winnersData", models.TextField(blank=True)),
                (
                    "created",
                    models.CharField(
                        default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow,
                        max_length=15,
                    ),
                ),
                ("tournamentProgressionData", models.TextField(blank=True)),
                ("tournamentSideData", models.TextField(blank=True)),
                ("tournamentPointsData", models.TextField(blank=True)),
                ("chatData", models.TextField(blank=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="MainT_creator_relName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nextRoundPlayers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="currentRoundPlayersRelName_MainT",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "startingPlayers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="startingPlayersRelName_MainT",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
