# Generated by Django 5.2.7 on 2025-11-23 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0048_alter_mini_tournaments_tournamenttype_and_more"),
        ("TGZ", "0023_tgz_game_relatedmaintournament"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Main_Tournaments",
            new_name="Main_Tournament",
        ),
    ]
