# Generated by Django 5.2.7 on 2025-11-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Lobby", "0049_rename_main_tournaments_main_tournament"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="main_tournament",
            name="creator",
        ),
    ]
