# Generated by Django 5.2.9 on 2025-12-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0050_remove_main_tournament_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileLanguage',
            field=models.CharField(choices=[('en-gb', 'English (United Kingdom)'), ('zh-hans', '简体中文'), ('es', 'Spanish (Spain)'), ('de', 'Deutsche')], default='en-gb', max_length=10),
        ),
    ]
