# Generated by Django 5.2.9 on 2026-01-02 16:18

import Lobby.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0053_update_cross_game_views_v2_20251224_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='timestamp',
            field=models.CharField(db_index=True, default=Lobby.models.get_default_timestamp, max_length=30),
        ),
    ]
