# Generated by Django 5.2.9 on 2026-01-15 22:43

import Lobby.sharedFunctions.sharedRefs
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0055_alter_main_tournament_gamecode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gameName",
                    models.CharField(
                        blank=True, max_length=120
                    ),
                ),
                (
                    "gameDescription",
                    models.CharField(
                        blank=True, max_length=120
                    ),
                ),
                (
                    "gameStatus",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "AVAILABLE"),
                            ("WAITING", "WAITING"),
                            ("PRIVATE", "PRIVATE"),
                            ("ACTIVE", "ACTIVE"),
                            ("FINISHED", "FINISHED"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=9,
                    ),
                ),
                ("playerOrderSeed", models.PositiveSmallIntegerField(default=0)),
                ("maxPlayers", models.PositiveSmallIntegerField(default=2)),
                ("turn", models.PositiveSmallIntegerField(default=0)),
                ("phase", models.PositiveSmallIntegerField(default=0)),
                ("kickoutDuration", models.PositiveSmallIntegerField(default=200)),
                ("gamePace", models.PositiveSmallIntegerField(default=30)),
                ("chatData", models.TextField(blank=True)),
                ("gameData", models.TextField(blank=True)),
                ("rewindData", models.TextField(blank=True)),
                ("rewindTempData", models.TextField(blank=True)),
                ("kickoutFlexiData", models.TextField(blank=True)),
                ("statsExcludedGame", models.BooleanField(default=False)),
                (
                    "zoomLevels",
                    models.CharField(default="[16, 16, 16, 16]", max_length=30),
                ),
                (
                    "latestUpdate",
                    models.CharField(
                        db_index=True,
                        default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow,
                        max_length=15,
                    ),
                ),
                (
                    "created",
                    models.CharField(
                        default=Lobby.sharedFunctions.sharedRefs.SR_getTimeNow,
                        max_length=15,
                    ),
                ),
                ("startingMap", models.CharField(blank=True, max_length=190)),
                ("startingOptions", models.CharField(blank=True, max_length=100)),
                (
                    "statsExcludeConsent",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "deleteGameVotes",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("activeVotes", models.JSONField(blank=True, default=dict, null=True)),
                ("gameCode", models.CharField(db_column="gameCode", max_length=255)),
                ("original_id", models.PositiveIntegerField(null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitedPlayers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invited_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kickedPlayers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="kicked_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("winner", models.BooleanField(default=False)),
                ("is_current", models.BooleanField(default=False)),
                ("has_chat_notification", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="Lobby.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
