# Generated by Django 5.2.9 on 2026-01-21 05:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0059_gameplayer_unique_constraint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="kickedPlayers",
        ),
    ]
