# Generated by Django 5.2.9 on 2026-01-21 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0061_alter_game_gamecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="relatedMainTournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintournamentGEN_relName",
                to="Lobby.main_tournament",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="relatedMiniTournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="minitournamentGEN_relName",
                to="Lobby.mini_tournaments",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="original_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
