# Generated by Django 5.2.9 on 2026-01-31 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # REMOVE: ("AQY", "0023_aqygame"),
        ("Lobby", "0068_migrate_tgz_games"),
    ]

    operations = [
        # DELETE the migrations.AlterField block entirely
    ]

