# Generated by Django 5.2.9 on 2026-02-02 09:54

from django.db import migrations


def migrate_tgz_automoves(apps, schema_editor):
    # App is deleted/unified, do nothing
    pass

class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0070_game_automoves"),
        # REMOVED: ("TGZ", "__first__"), <-- This was the cause of the Circular Dependency
    ]

    operations = [
        migrations.RunPython(migrate_tgz_automoves, migrations.RunPython.noop),
    ]
