# Generated by Django 5.2.9 on 2026-02-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0071_migrate_tgz_automoves"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="externalTournamentGame",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="tournamentGame",
            field=models.BooleanField(default=False),
        ),
    ]
