# Generated by Django 5.2.9 on 2026-02-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0073_populate_tournament_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='relatedTournament',
        ),
    ]
