# Generated by Django 5.2.9 on 2026-02-04 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0074_remove_game_relatedtournament"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="playersPreMoveData",
            field=models.TextField(blank=True),
        ),
        
    ]
