# Generated by Django 5.2.9 on 2026-02-08 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0076_migrate_ind_games"),
    ]

    operations = [

    ]
