# Generated by Django 5.2.9 on 2026-02-11 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0079_migrate_bus_games"),
    ]

    operations = [

    ]
