# Generated by Django 5.2.9 on 2026-02-14 03:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0082_migrate_fcm_games"),
    ]

    operations = [

    ]
