# Generated by Django 5.2.9 on 2026-02-15 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0048_hcgame'),
        ('Lobby', '0083_remove_game_relatedfcmtournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='relatedHCTournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hctournamentGEN_relName', to='HC.hc_tournament'),
        ),
        migrations.AddField(
            model_name='game',
            name='currentPlayersInTurnOrder',
            field=models.CharField(blank=True, null=True, default=None, max_length=150),
        ),
    ]
