# Generated by Django 5.2.9 on 2026-02-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0083_remove_game_relatedfcmtournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='serverRemainingPlayerOrderByNames',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
