# Generated by Django 5.2.9 on 2026-02-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0084_game_serverremainingplayerorderbynames'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameDataBLOB',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
