# Generated by Django 5.2.9 on 2026-02-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0085_game_gamedatablob"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameplayer",
            name="moveDataJSON",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
