# Generated by Django 5.2.9 on 2026-02-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0086_gameplayer_movedatajson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='serverRemainingPlayerOrderByNames',
        ),
    ]
