# Generated by Django 5.2.9 on 2026-02-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0087_remove_game_serverremainingplayerorderbynames"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="serverRemainingPlayerOrderByNames",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
