# Generated by Django 5.2.9 on 2026-02-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0089_alter_changelog_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="currentPlayersInTurnOrder",
            field=models.CharField(blank=True, null=True, default=None, max_length=150),
        ),
    ]
