# Generated by Django 5.2.9 on 2026-02-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0092_remove_queryable_game_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='relatedHCTournament',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='moveDataJSON',
        ),
    ]
