# Generated by Django 5.2.9 on 2026-02-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0093_remove_game_relatedhctournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='moveDataJSON',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
