# Generated by Django 5.2.9 on 2026-02-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0094_gameplayer_movedatajson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='serverRemainingPlayerOrderByNames',
            new_name='serverCurrentPlayerNamesInTurnOrder',
        ),
        migrations.RemoveField(
            model_name='game',
            name='deleteGameVotes',
        ),
        migrations.RemoveField(
            model_name='game',
            name='statsExcludeConsent',
        ),
    ]
