# Generated by Django 5.2.9 on 2026-02-23 00:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Lobby", "0097_migrate_kfw_games"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="gameDataBLOB",
        ),
    ]
