# Generated by Django 5.2.9 on 2026-02-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0098_remove_game_gamedatablob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='serverCurrentPlayerNamesInTurnOrder',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
