# Generated by Django 5.2.9 on 2026-03-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0099_alter_game_servercurrentplayernamesinturnorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameCode',
            field=models.CharField(choices=[('FCM', 'Food Chain Magnate'), ('HLC', 'Horseless Carriage'), ('BUS', 'BUS'), ('TGZ', 'The Great Zimbabwe'), ('CNS', 'Cannes'), ('AQY', 'Antiquity'), ('IND', 'Indonesia'), ('KFW', 'Keyflower'), ('WEB', 'Web'), ('RNB', 'Roads & Boats')], db_column='gameCode', default='FCM', max_length=3),
        ),
        migrations.AlterField(
            model_name='main_tournament',
            name='gameCode',
            field=models.CharField(choices=[('FCM', 'Food Chain Magnate'), ('HLC', 'Horseless Carriage'), ('BUS', 'BUS'), ('TGZ', 'The Great Zimbabwe'), ('CNS', 'Cannes'), ('AQY', 'Antiquity'), ('IND', 'Indonesia'), ('KFW', 'Keyflower'), ('WEB', 'Web'), ('RNB', 'Roads & Boats')], default='FCM', max_length=3),
        ),
        migrations.AlterField(
            model_name='mini_tournaments',
            name='gameCode',
            field=models.CharField(choices=[('FCM', 'Food Chain Magnate'), ('HLC', 'Horseless Carriage'), ('TGZ', 'The Great Zimbabwe'), ('CNS', 'Cannes'), ('AQY', 'Antiquity'), ('IND', 'Indonesia'), ('KFW', 'Keyflower')], default='FCM', max_length=3),
        ),
    ]
