# Generated by Django 5.2.9 on 2026-04-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0100_alter_game_gamecode_alter_main_tournament_gamecode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Database Lock',
                'verbose_name_plural': 'Database Locks',
            },
        ),
    ]
