# Generated by Django 5.2.9 on 2026-04-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0101_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
