# Generated by Django 5.2.9 on 2026-04-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0102_profile_discord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='startingMap',
            field=models.TextField(blank=True, default=''),
        ),
    ]
