# Generated by Django 5.2.9 on 2026-04-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0106_delete_mini_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferredRNBoptions',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
