# Generated by Django 5.2.9 on 2026-05-06 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0107_profile_preferredrnboptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='notes',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
