# Generated by Django 5.2.9 on 2026-05-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0108_alter_gameplayer_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournamentStatus',
            field=models.CharField(choices=[('PD', 'Pending'), ('OP', 'Open'), ('PR', 'Private'), ('IP', 'In Progress'), ('FN', 'Finished')], default='OP', max_length=2),
        ),
    ]
