# Generated by Django 5.2.9 on 2026-06-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0113_profile_availability_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='availabilityAnchor',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
