# Generated by Django 5.2.9 on 2026-09-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0114_gameplayer_availabilityanchor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameCode',
            field=models.CharField(choices=[('FCM', 'Food Chain Magnate'), ('HLC', 'Horseless Carriage'), ('BUS', 'BUS'), ('TGZ', 'The Great Zimbabwe'), ('CNS', 'Cannes'), ('AQY', 'Antiquity'), ('IND', 'Indonesia'), ('KFW', 'Keyflower'), ('WEB', 'Web'), ('RNB', 'Roads & Boats'), ('URR', 'UR: 1830 BC'), ('DDL', 'Duck Dealer')], db_column='gameCode', default='FCM', max_length=3),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='gameCode',
            field=models.CharField(choices=[('FCM', 'Food Chain Magnate'), ('HLC', 'Horseless Carriage'), ('BUS', 'BUS'), ('TGZ', 'The Great Zimbabwe'), ('CNS', 'Cannes'), ('AQY', 'Antiquity'), ('IND', 'Indonesia'), ('KFW', 'Keyflower'), ('WEB', 'Web'), ('RNB', 'Roads & Boats'), ('URR', 'UR: 1830 BC'), ('DDL', 'Duck Dealer')], default='FCM', max_length=3),
        ),
    ]
