# Generated by Django 5.2.9 on 2026-10-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0115_alter_game_gamecode_alter_tournament_gamecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='startingMap',
            field=models.TextField(blank=True, default=''),
        ),
    ]
