# Generated by Django 5.2.9 on 2026-10-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0116_tournament_startingmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileLanguage',
            field=models.CharField(choices=[('en-gb', 'English (United Kingdom)'), ('zh-hans', '简体中文'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano')], default='en-gb', max_length=10),
        ),
    ]
