# Generated by Django 3.2.3 on 2024-06-07 03:01

import Lobby.sharedFunctions.sharedFunctions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AQY_Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gameName",
                    models.CharField(blank=True, db_collation="utf8mb4_general_ci", max_length=120),
                ),
                (
                    "gameDescription",
                    models.CharField(blank=True, db_collation="utf8mb4_general_ci", max_length=120),
                ),
                (
                    "gameStatus",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "AVAILABLE"),
                            ("WAITING", "WAITING"),
                            ("ACTIVE", "ACTIVE"),
                            ("FINISHED", "FINISHED"),
                        ],
                        default="AVAILABLE",
                        max_length=9,
                    ),
                ),
                (
                    "latestUpdate",
                    models.CharField(
                        default=Lobby.sharedFunctions.sharedFunctions.SF_getTimeNow,
                        max_length=15,
                    ),
                ),
                ("startingOptions", models.CharField(blank=True, max_length=20)),
                ("currentPlayers", models.CharField(blank=True, max_length=100)),
                ("playerOrderSeed", models.PositiveSmallIntegerField(default=0)),
                ("maxPlayers", models.PositiveSmallIntegerField(default=2)),
                ("turn", models.PositiveSmallIntegerField(default=1)),
                ("phase", models.PositiveSmallIntegerField(default=0)),
                ("kickoutDuration", models.PositiveSmallIntegerField(default=200)),
                ("gamePace", models.PositiveSmallIntegerField(default=40)),
                (
                    "created",
                    models.CharField(
                        default=Lobby.sharedFunctions.sharedFunctions.SF_getTimeNow,
                        max_length=15,
                    ),
                ),
                (
                    "zoomLevels",
                    models.CharField(default="[16, 16, 16, 16]", max_length=30),
                ),
                ("statsExcludeConsent", models.CharField(default="0000", max_length=4)),
                ("player0currentMoveData", models.TextField(blank=True)),
                ("player1currentMoveData", models.TextField(blank=True)),
                ("player2currentMoveData", models.TextField(blank=True)),
                ("player3currentMoveData", models.TextField(blank=True)),
                ("chatData", models.TextField(blank=True)),
                ("player0notes", models.TextField(blank=True)),
                ("player1notes", models.TextField(blank=True)),
                ("player2notes", models.TextField(blank=True)),
                ("player3notes", models.TextField(blank=True)),
                ("gameData", models.TextField(blank=True)),
                ("rewindData", models.TextField(blank=True)),
                ("rewindTempData", models.TextField(blank=True)),
                ("statsExcludedGame", models.BooleanField(default=False)),
                ("kickoutFlexiData", models.TextField(blank=True)),
                (
                    "allPlayers",
                    models.ManyToManyField(related_name="AQYallPlayersRelName", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        default="admin",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="AQYgame_creator_relName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        default="admin",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="AQYgame_host_relName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitedPlayers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="AQYinvitedPlayersRelName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kickedPlayers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="AQYkickedPlayersRelName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "missingPlayers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="AQYmissingPlayersRelName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "playersWithChatNotification",
                    models.ManyToManyField(
                        blank=True,
                        related_name="AQYplayersWithChatNotificationName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="AQYgame_winner_relName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
