# Generated by Django 3.2.3 on 2024-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQY', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqy_game',
            name='player0currentMoveTime',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='aqy_game',
            name='player1currentMoveTime',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='aqy_game',
            name='player2currentMoveTime',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='aqy_game',
            name='player3currentMoveTime',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
