# Generated by Django 5.2.9 on 2026-04-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AQY', '0001_initial'),
        ('Lobby', '0107_profile_preferredrnboptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AQYMainTournament',
            fields=[
            ],
            options={
                'verbose_name': 'AQY Main Tournament',
                'verbose_name_plural': 'AQY Main Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
        migrations.CreateModel(
            name='AQYMiniTournament',
            fields=[
            ],
            options={
                'verbose_name': 'AQY Mini Tournament',
                'verbose_name_plural': 'AQY Mini Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
    ]
