# Generated by Django 3.2.3 on 2024-09-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQY', '0003_auto_20240911_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqy_game',
            name='playerTradeData',
            field=models.TextField(blank=True),
        ),
    ]
