# Generated by Django 3.2.3 on 2024-09-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQY', '0004_aqy_game_playertradedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqy_game',
            name='startingMap',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
