# Generated by Django 3.2.3 on 2025-01-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AQY", "0007_alter_aqy_game_gamestatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aqy_tournament",
            name="tournamentType",
            field=models.CharField(
                choices=[
                    ("RR", "Rounds"),
                    ("KO", "Knockout"),
                    ("TL", "Two Lives"),
                    ("PT", "Points"),
                ],
                default="RR",
                max_length=2,
            ),
        ),
    ]
