# Generated by Django 5.2.9 on 2026-01-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQY', '0016_aqy_game_relatedminitournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqy_game',
            name='turn',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
