# Generated by Django 5.2.9 on 2026-01-14 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AQY", "0018_alter_aqy_game_gamepace_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aqy_game",
            name="deleteGameVotes",
        ),
    ]
