# Generated by Django 5.2.9 on 2026-01-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AQY", "0020_aqy_game_deletegamevotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aqy_game",
            name="startingMap",
            field=models.CharField(blank=True, max_length=190),
        ),
        migrations.AlterField(
            model_name="aqy_game",
            name="statsExcludeConsent",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
