# Generated by Django 5.2.9 on 2026-02-03 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AQY", "0024_aqy_game_automoves"),
        ("Lobby", "0074_remove_game_relatedtournament"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aqy_game",
            name="relatedTournament",
        ),
        migrations.DeleteModel(
            name="AQY_Tournament",
        ),
    ]
