# Generated by Django 5.2.9 on 2026-02-04 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AQY", "0025_remove_aqy_game_relatedtournament_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AQY_Game",
        ),
    ]
