# Generated by Django 3.2.3 on 2023-09-23 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus_Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gameName",
                    models.CharField(blank=True, default="[Bus Game]", max_length=120),
                ),
                ("gameDescription", models.CharField(blank=True, max_length=120)),
                (
                    "gameStatus",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "AVAILABLE"),
                            ("WAITING", "WAITING"),
                            ("ACTIVE", "ACTIVE"),
                            ("FINISHED", "FINISHED"),
                        ],
                        default="AVAILABLE",
                        max_length=30,
                    ),
                ),
                ("latestUpdate", models.CharField(max_length=30)),
                ("startingOptions", models.CharField(blank=True, max_length=70)),
                ("currentPlayers", models.CharField(blank=True, max_length=100)),
                ("playerOrderSeed", models.PositiveSmallIntegerField(default=0)),
                ("maxPlayers", models.PositiveSmallIntegerField(default=3)),
                ("turn", models.PositiveSmallIntegerField(default=0)),
                ("phase", models.PositiveSmallIntegerField(default=0)),
                ("kickoutDuration", models.PositiveSmallIntegerField(default=200)),
                ("gamePace", models.PositiveSmallIntegerField(default=20)),
                ("created", models.CharField(max_length=30)),
                (
                    "zoomLevels",
                    models.CharField(default="[120,120,120]", max_length=30),
                ),
                ("rewindConsent", models.CharField(default="[0,0,0]", max_length=10)),
                (
                    "statsExcludeConsent",
                    models.CharField(default="[0,0,0]", max_length=10),
                ),
                ("chatData", models.TextField(blank=True)),
                ("player0notes", models.TextField(blank=True)),
                ("player1notes", models.TextField(blank=True)),
                ("player2notes", models.TextField(blank=True)),
                ("player3notes", models.TextField(blank=True)),
                ("player4notes", models.TextField(blank=True)),
                ("gameData", models.TextField(blank=True)),
                ("rewindData", models.TextField(blank=True)),
                ("rewindTempData", models.TextField(blank=True)),
                ("tournamentGame", models.BooleanField(default=False)),
                ("statsExcludedGame", models.BooleanField(default=False)),
                (
                    "allPlayers",
                    models.ManyToManyField(
                        related_name="BusAllPlayersRelName", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="BusGame_creator_relName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="BusGame_host_relName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitedPlayers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="BusInvitedPlayersRelName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kickedPlayers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="BusKickedPlayersRelName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "missingPlayers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="BusMissingPlayersRelName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "playersWithChatNotification",
                    models.ManyToManyField(
                        blank=True,
                        related_name="BusPlayersWithChatNotificationName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="BusGame_winner_relName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
