# Generated by Django 5.2.9 on 2026-03-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lobby', '0100_alter_game_gamecode_alter_main_tournament_gamecode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BUSgame',
            fields=[
            ],
            options={
                'verbose_name': 'BUS_Game',
                'verbose_name_plural': 'BUS_Games',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.game',),
        ),
    ]
