# Generated by Django 5.2.9 on 2026-04-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BUS', '0001_initial'),
        ('Lobby', '0107_profile_preferredrnboptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BUSMainTournament',
            fields=[
            ],
            options={
                'verbose_name': 'BUS Main Tournament',
                'verbose_name_plural': 'BUS Main Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
        migrations.CreateModel(
            name='BUSMiniTournament',
            fields=[
            ],
            options={
                'verbose_name': 'BUS Mini Tournament',
                'verbose_name_plural': 'BUS Mini Tournaments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lobby.tournament',),
        ),
    ]
