# Generated by Django 3.2.3 on 2023-12-30 05:13

import Lobby.sharedFunctions.sharedFunctions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bus", "0002_auto_20231227_0215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus_game",
            name="created",
            field=models.CharField(
                default=Lobby.sharedFunctions.sharedFunctions.SF_getTimeNow,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="bus_game",
            name="latestUpdate",
            field=models.CharField(
                default=Lobby.sharedFunctions.sharedFunctions.SF_getTimeNow,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="bus_tournament",
            name="created",
            field=models.CharField(
                default=Lobby.sharedFunctions.sharedFunctions.SF_getTimeNow,
                max_length=30,
            ),
        ),
    ]
