# Generated by Django 3.2.3 on 2025-07-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0008_alter_bus_tournament_tournamenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_game',
            name='deleteGameVotes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='bus_game',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bus_tournament',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
