# Generated by Django 3.2.3 on 2025-07-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bus", "0009_auto_20250719_1321"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus_tournament",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
