# Generated by Django 5.2.7 on 2025-12-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bus", "0014_alter_bus_game_gamestatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus_tournament",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
