# Generated by Django 5.2.9 on 2026-01-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0017_alter_bus_game_gamepace_alter_bus_game_latestupdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus_game',
            name='deleteGameVotes',
        ),
    ]
