# Generated by Django 5.2.9 on 2026-01-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BUS", "0019_bus_game_deletegamevotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus_game",
            name="startingMap",
            field=models.CharField(blank=True, max_length=190),
        ),
    ]
