# Generated by Django 5.2.9 on 2026-02-10 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Bus", "0023_bus_game_automoves"),
        ("Lobby", "0079_migrate_bus_games"),
    ]

    operations = [
        migrations.CreateModel(
            name="Busgame",
            fields=[],
            options={
                "verbose_name": "Bus_Game",
                "verbose_name_plural": "Bus_Games",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Lobby.game",),
        ),
    ]
