# Generated by Django 5.2.9 on 2026-02-11 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BUS", "0024_busgame"),
        ("Lobby", "0080_remove_game_relatedbustournament"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus_game",
            name="relatedTournament",
        ),
        migrations.DeleteModel(
            name="Bus_Tournament",
        ),
    ]
