# Generated by Django 5.2.9 on 2026-02-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0025_remove_bus_game_relatedtournament_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus_Game',
        ),
    ]
